# Generated by Django 5.2.7 on 2025-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('attack_power', models.IntegerField(default=0)),
                ('defense_power', models.IntegerField(default=0)),
            ],
        ),
    ]
