# Generated by Django 5.2.7 on 2025-10-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="armor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_armor",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="boots",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_boots",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="character_class",
            field=models.CharField(
                choices=[
                    ("Warrior", "Warrior"),
                    ("Mage", "Mage"),
                    ("Rogue", "Rogue"),
                    ("Shilen Elder", "Shilen Elder"),
                    ("Death Knight", "Death Knight"),
                ],
                default="Warrior",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="earring_left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_earring_left",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="earring_right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_earring_right",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="gloves",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_gloves",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="necklace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_necklace",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="ring_left",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_ring_left",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="ring_right",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_ring_right",
                to="items.item",
            ),
        ),
    ]
