# Generated by Django 5.2.7 on 2025-10-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_character_armor_character_boots_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physical_attack", models.IntegerField(default=0)),
                ("magical_attack", models.IntegerField(default=0)),
                ("physical_defense", models.IntegerField(default=0)),
                ("magic_resistance", models.IntegerField(default=0)),
                ("accuracy", models.IntegerField(default=0)),
                (
                    "critical_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("critical_damage", models.IntegerField(default=0)),
                ("damage_reduction", models.IntegerField(default=0)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_stats",
                        to="items.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubclassStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subclass_level", models.IntegerField(default=0)),
                ("subclass_bonus_hp", models.IntegerField(default=0)),
                ("subclass_bonus_mp", models.IntegerField(default=0)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclass_stats",
                        to="items.character",
                    ),
                ),
            ],
        ),
    ]
