# Generated by Django 5.2.7 on 2025-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_bonusstats_subclassstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
