# Generated by Django 5.2.7 on 2025-10-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_icon_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Character update', max_length=255)),
                ('total_score', models.FloatField()),
                ('base_score', models.FloatField()),
                ('item_score', models.FloatField()),
                ('bonus_score', models.FloatField()),
                ('subclass_score', models.FloatField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_logs', to='items.character')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
