# Generated by Django 5.2.7 on 2025-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_gearscorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enchant_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
