# Generated by Django 5.2.7 on 2025-10-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_enchant_level_item_grade_item_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendaryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_file', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Dual Blades', 'Dual Blades'), ('Dagger', 'Dagger'), ('Orb', 'Orb'), ('Staff', 'Staff'), ('Bow', 'Bow'), ('One-handed sword', 'One-handed sword'), ('Spear', 'Spear')], default='Warrior', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='legendary_classes',
            field=models.ManyToManyField(blank=True, to='items.legendaryclass'),
        ),
    ]
