# Generated by Django 5.2.7 on 2025-10-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_legendaryclass_alter_character_character_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='clan',
            field=models.CharField(blank=True, choices=[('Valkyrie', 'Valkyrie')], default='Valkyrie', max_length=100),
        ),
    ]
