# Generated by Django 5.2.7 on 2025-10-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_character_clan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_classes_count', models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-19', '10-19'), ('20-29', '20-29'), ('30-39', '30-39')], max_length=10)),
                ('epic_agathions_count', models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-20', '10-20')], max_length=10)),
                ('soulshot_level', models.CharField(blank=True, choices=[('5-3', '5-3 and lower'), ('6', 'from 6 to 6-3'), ('7', 'from 7 to 7-3'), ('8', 'from 8 to 8-3'), ('9', 'from 9 to 9-3'), ('10', 'from 10 to 10-2'), ('10-3', '10-3')], max_length=10)),
                ('valor_level', models.CharField(blank=True, choices=[('5-3', '5-3 and lower'), ('6', 'from 6 to 6-3'), ('7', 'from 7 to 7-3'), ('8', 'from 8 to 8-3'), ('9', 'from 9 to 9-3'), ('10', 'from 10 to 10-2'), ('10-3', '10-3')], max_length=10)),
                ('soul_prog_attack', models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10)),
                ('soul_prog_defense', models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10)),
                ('soul_prog_blessing', models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10)),
                ('enchant_bracelet_holy_prot', models.IntegerField(choices=[(0, 'Not specified'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0)),
                ('enchant_bracelet_influence', models.IntegerField(choices=[(0, 'Not specified'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0)),
                ('enchant_earring_earth', models.IntegerField(choices=[(0, 'Not specified'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0)),
                ('enchant_earring_fire', models.IntegerField(choices=[(0, 'Not specified'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0)),
                ('enchant_seal_eva', models.IntegerField(choices=[(0, 'Not specified'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='items.character')),
            ],
        ),
    ]
