# Generated by Django 5.2.7 on 2025-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_characterattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InheritorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegendaryAgathion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_file', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='inheritor_books',
            field=models.ManyToManyField(blank=True, to='items.inheritorbook'),
        ),
        migrations.AddField(
            model_name='character',
            name='legendary_agathions',
            field=models.ManyToManyField(blank=True, to='items.legendaryagathion'),
        ),
    ]
