# Generated by Django 5.2.7 on 2025-10-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_inheritorbook_legendaryagathion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusstats',
            name='accuracy',
            field=models.IntegerField(default=0, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='critical_damage',
            field=models.IntegerField(default=0, verbose_name='Critical Damage'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='critical_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Critical Rate'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='damage_reduction',
            field=models.IntegerField(default=0, verbose_name='Damage Reduction'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='magic_resistance',
            field=models.IntegerField(default=0, verbose_name='Magic Resistance'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='magical_attack',
            field=models.IntegerField(default=0, verbose_name='Magical Attack'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='physical_attack',
            field=models.IntegerField(default=0, verbose_name='Physical Attack'),
        ),
        migrations.AlterField(
            model_name='bonusstats',
            name='physical_defense',
            field=models.IntegerField(default=0, verbose_name='Physical Defense'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_armor', to='items.item', verbose_name='Baju Zirah'),
        ),
        migrations.AlterField(
            model_name='character',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_boots', to='items.item', verbose_name='Sepatu'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Dual Blades', 'Dual Blades'), ('Dagger', 'Dagger'), ('Orb', 'Orb'), ('Staff', 'Staff'), ('Bow', 'Panah'), ('One-handed sword', 'Pedang Satu Tangan'), ('Spear', 'Tombak')], default='Spear', max_length=100, verbose_name='Kelas'),
        ),
        migrations.AlterField(
            model_name='character',
            name='clan',
            field=models.CharField(blank=True, choices=[('Valkyrie', 'Valkyrie')], default='Valkyrie', max_length=100, verbose_name='Clan'),
        ),
        migrations.AlterField(
            model_name='character',
            name='earring_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_earring_left', to='items.item', verbose_name='Anting Kiri'),
        ),
        migrations.AlterField(
            model_name='character',
            name='earring_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_earring_right', to='items.item', verbose_name='Anting Kanan'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gloves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_gloves', to='items.item', verbose_name='Sarung Tangan'),
        ),
        migrations.AlterField(
            model_name='character',
            name='helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_helmet', to='items.item', verbose_name='Helm'),
        ),
        migrations.AlterField(
            model_name='character',
            name='legendary_agathions',
            field=models.ManyToManyField(blank=True, to='items.legendaryagathion', verbose_name='Agathion Legendaris'),
        ),
        migrations.AlterField(
            model_name='character',
            name='legendary_classes',
            field=models.ManyToManyField(blank=True, to='items.legendaryclass', verbose_name='Kelas Legendaris'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='character',
            name='main_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon', to='items.item', verbose_name='Senjata Utama'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Karakter'),
        ),
        migrations.AlterField(
            model_name='character',
            name='necklace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_necklace', to='items.item', verbose_name='Kalung'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ring_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring_left', to='items.item', verbose_name='Cincin Kiri'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ring_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring_right', to='items.item', verbose_name='Cincin Kanan'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='enchant_bracelet_holy_prot',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0, verbose_name='Enchant Bracelet of Holy Protection'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='enchant_bracelet_influence',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0, verbose_name='Enchant Bracelet of Influence'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='enchant_earring_earth',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0, verbose_name="Enchant Earth Dragon's Earring"),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='enchant_earring_fire',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0, verbose_name="Enchant Fire Dragon's Earring"),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='enchant_seal_eva',
            field=models.IntegerField(choices=[(0, 'Tidak ada'), (1, '+1'), (2, '+2'), (3, '+3'), (4, '+4'), (5, '+5'), (6, '+6'), (7, '+7'), (8, '+8')], default=0, verbose_name="Enchant Eva's Seal"),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='epic_agathions_count',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-20', '10-20')], max_length=10, verbose_name='Jumlah Agathion Epic'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='epic_classes_count',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-19', '10-19'), ('20-29', '20-29'), ('30-39', '30-39')], max_length=10, verbose_name='Jumlah Kelas Epic'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='inheritor_books',
            field=models.ManyToManyField(blank=True, to='items.inheritorbook', verbose_name='Buku Inheritor'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soul_prog_attack',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10, verbose_name='Soul Progression Attack'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soul_prog_blessing',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10, verbose_name='Soul Progression Blessing'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soul_prog_defense',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10, verbose_name='Soul Progression Defense'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soulshot_level',
            field=models.CharField(blank=True, choices=[('5-3', '5-3 ke bawah'), ('6', 'dari 6 sampai 6-3'), ('7', 'dari 7 sampai 7-3'), ('8', 'dari 8 sampai 8-3'), ('9', 'dari 9 sampai 9-3'), ('10', 'dari 10 sampai 10-2'), ('10-3', '10-3')], max_length=10, verbose_name='Level Soulshot'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='valor_level',
            field=models.CharField(blank=True, choices=[('5-3', '5-3 ke bawah'), ('6', 'dari 6 sampai 6-3'), ('7', 'dari 7 sampai 7-3'), ('8', 'dari 8 sampai 8-3'), ('9', 'dari 9 sampai 9-3'), ('10', 'dari 10 sampai 10-2'), ('10-3', '10-3')], max_length=10, verbose_name='Level Valor'),
        ),
        migrations.AlterField(
            model_name='gearscorelog',
            name='reason',
            field=models.CharField(default='Pembaruan Karakter', max_length=255, verbose_name='Alasan'),
        ),
        migrations.AlterField(
            model_name='inheritorbook',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='item',
            name='attack_power',
            field=models.IntegerField(default=0, verbose_name='Attack Power'),
        ),
        migrations.AlterField(
            model_name='item',
            name='defense_power',
            field=models.IntegerField(default=0, verbose_name='Defense Power'),
        ),
        migrations.AlterField(
            model_name='item',
            name='enchant_level',
            field=models.IntegerField(default=0, verbose_name='Level Enchant'),
        ),
        migrations.AlterField(
            model_name='item',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Ikon'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=50, verbose_name='Tipe Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='legendaryagathion',
            name='icon_file',
            field=models.CharField(blank=True, max_length=100, verbose_name='File Ikon'),
        ),
        migrations.AlterField(
            model_name='legendaryagathion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='legendaryclass',
            name='icon_file',
            field=models.CharField(blank=True, max_length=100, verbose_name='File Ikon'),
        ),
        migrations.AlterField(
            model_name='legendaryclass',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='subclassstats',
            name='subclass_bonus_hp',
            field=models.IntegerField(default=0, verbose_name='Bonus HP Subclass'),
        ),
        migrations.AlterField(
            model_name='subclassstats',
            name='subclass_bonus_mp',
            field=models.IntegerField(default=0, verbose_name='Bonus MP Subclass'),
        ),
        migrations.AlterField(
            model_name='subclassstats',
            name='subclass_level',
            field=models.IntegerField(default=0, verbose_name='Level Subclass'),
        ),
    ]
