# Generated by Django 5.2.7 on 2025-10-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_bonusstats_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inheritorbook',
            name='icon_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Ikon'),
        ),
    ]
