# Generated by Django 5.2.7 on 2026-01-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_skill_characterattributes_pvp_belt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterattributes",
            name="stat_acc",
            field=models.IntegerField(
                default=0,
                help_text="Total accuracy stat",
                verbose_name="ACC (Accuracy)",
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_def",
            field=models.IntegerField(
                default=0, help_text="Total defense stat", verbose_name="DEF (Defense)"
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_dmg",
            field=models.IntegerField(
                default=0, help_text="Total damage stat", verbose_name="DMG (Damage)"
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_guardian",
            field=models.IntegerField(
                default=0,
                help_text="Guardian level (multiplied by 10 in score)",
                verbose_name="Guardian",
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_reduc",
            field=models.IntegerField(
                default=0,
                help_text="Damage reduction stat (multiplied by 3 in score)",
                verbose_name="REDUC (Damage Reduction)",
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_resist",
            field=models.IntegerField(
                default=0,
                help_text="Magic/status resistance stat",
                verbose_name="RESIST (Resistance)",
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_skill_dmg_boost",
            field=models.IntegerField(
                default=0,
                help_text="Skill damage boost (multiplied by 2 in score)",
                verbose_name="Skill DMG Boost",
            ),
        ),
        migrations.AddField(
            model_name="characterattributes",
            name="stat_wpn_dmg_boost",
            field=models.IntegerField(
                default=0,
                help_text="Weapon damage boost stat",
                verbose_name="Weapon DMG Boost",
            ),
        ),
    ]
