# Generated by Django 5.2.7 on 2026-01-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_characterattributes_stat_acc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gearscorelog",
            name="base_score",
        ),
        migrations.RemoveField(
            model_name="gearscorelog",
            name="bonus_score",
        ),
        migrations.RemoveField(
            model_name="gearscorelog",
            name="item_score",
        ),
        migrations.RemoveField(
            model_name="gearscorelog",
            name="subclass_score",
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="acc",
            field=models.IntegerField(default=0, verbose_name="ACC"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="def_stat",
            field=models.IntegerField(default=0, verbose_name="DEF"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="dmg",
            field=models.IntegerField(default=0, verbose_name="DMG"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="guardian",
            field=models.IntegerField(default=0, verbose_name="Guardian"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="reduc",
            field=models.IntegerField(default=0, verbose_name="REDUC"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="resist",
            field=models.IntegerField(default=0, verbose_name="RESIST"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="skill_dmg_boost",
            field=models.IntegerField(default=0, verbose_name="Skill DMG Boost"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="soulshot",
            field=models.IntegerField(default=0, verbose_name="Soulshot"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="valor",
            field=models.IntegerField(default=0, verbose_name="Valor"),
        ),
        migrations.AddField(
            model_name="gearscorelog",
            name="wpn_dmg_boost",
            field=models.IntegerField(default=0, verbose_name="Wpn DMG Boost"),
        ),
    ]
