# Generated by Django 5.2.7 on 2026-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_remove_gearscorelog_base_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='stat_conquer',
            field=models.IntegerField(default=0, help_text='Conquer level (multiplied by 10 in score)', verbose_name='Conquer'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='total_legend_codex',
            field=models.IntegerField(default=0, help_text='Total Legend Class & Agathion Codex (multiplied by 3 in score)', verbose_name='Total Legend Codex'),
        ),
    ]
