# Generated by Django 5.2.7 on 2026-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_characterattributes_stat_conquer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterattributes',
            name='skills',
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_absolute_spear',
            field=models.BooleanField(default=False, verbose_name='Absolute Spear'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_disarm',
            field=models.BooleanField(default=False, verbose_name='Disarm'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_earthquake_stomp',
            field=models.BooleanField(default=False, verbose_name='Earthquake Stomp'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_frenzy',
            field=models.BooleanField(default=False, verbose_name='Frenzy'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_giant_stomp',
            field=models.BooleanField(default=False, verbose_name='Giant Stomp'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_infinity_strike',
            field=models.BooleanField(default=False, verbose_name='Infinity Strike'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_rolling_thunder',
            field=models.BooleanField(default=False, verbose_name='Rolling Thunder'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='skill_vital_destruction',
            field=models.BooleanField(default=False, verbose_name='Vital Destruction'),
        ),
    ]
