# Generated by Django 5.2.7 on 2026-01-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_characteristicsstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterattributes',
            name='epic_agathions_count',
            field=models.IntegerField(default=0, verbose_name='Legend Agathion Point'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='epic_classes_count',
            field=models.IntegerField(default=0, verbose_name='Legend Class Point'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soulshot_level',
            field=models.IntegerField(default=0, verbose_name='Soulshot Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='valor_level',
            field=models.IntegerField(default=0, verbose_name='Valor Level'),
        ),
    ]
