# Generated by Django 5.2.7 on 2026-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_characterattributes_epic_agathions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclassstats',
            name='bow_absolute_piercing',
            field=models.BooleanField(default=False, verbose_name='Absolute Piercing'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_death_sting',
            field=models.BooleanField(default=False, verbose_name='Death Sting'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_elimination',
            field=models.BooleanField(default=False, verbose_name='Elimination'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_entangle',
            field=models.BooleanField(default=False, verbose_name='Entangle'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_impact_shot',
            field=models.BooleanField(default=False, verbose_name='Impact Shot'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_mana_seeker',
            field=models.BooleanField(default=False, verbose_name='Mana Seeker'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_pinpoint_shot',
            field=models.BooleanField(default=False, verbose_name='Pinpoint Shot'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_real_target',
            field=models.BooleanField(default=False, verbose_name='Real Target'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='bow_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('bow_peril', 'Bow of Peril'), ('archangel', 'Archangel Bow'), ('carnium', 'Carnium Bow'), ('soul', 'Soul Bow'), ('shyeed', "Shyeed's Bow")], default='none', max_length=50, verbose_name='Bow Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_assassin_vision',
            field=models.BooleanField(default=False, verbose_name="Assassin's Vision"),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_hide',
            field=models.BooleanField(default=False, verbose_name='Hide'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_marionette',
            field=models.BooleanField(default=False, verbose_name='Marionette'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_phantom_blade',
            field=models.BooleanField(default=False, verbose_name='Phantom Blade'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_reset_movement',
            field=models.BooleanField(default=False, verbose_name='Reset Movement'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_shadow_blade',
            field=models.BooleanField(default=False, verbose_name='Shadow Blade'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_shadow_step',
            field=models.BooleanField(default=False, verbose_name='Shadow Step'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_venom',
            field=models.BooleanField(default=False, verbose_name='Venom'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dagger_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('demon', "Demon's Dagger"), ('archangel', 'Archangel Slayer'), ('cruma', "Cruma's Horn"), ('soul', 'Soul Separator'), ('naga', 'Naga Storm')], default='none', max_length=50, verbose_name='Dagger Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_berserker',
            field=models.BooleanField(default=False, verbose_name='Berserker'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_breaking_armor',
            field=models.BooleanField(default=False, verbose_name='Breaking Armor'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_dance_of_fury',
            field=models.BooleanField(default=False, verbose_name='Dance of Fury'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_detect_weakness',
            field=models.BooleanField(default=False, verbose_name='Detect Weakness'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_dual_impact',
            field=models.BooleanField(default=False, verbose_name='Dual Impact'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_dual_parrying',
            field=models.BooleanField(default=False, verbose_name='Dual Parrying'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_sonic_blaster',
            field=models.BooleanField(default=False, verbose_name='Sonic Blaster'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_triple_slash',
            field=models.BooleanField(default=False, verbose_name='Triple Slash'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualblade_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower'), ('tallum', 'Tallum Dual Blades'), ('archangel', 'Archangel Dual Blades'), ('dark_legion', "Dark Legion's Edge"), ('mardil', "Mardil's Rage"), ('astaroth', "Astaroth's Blades")], default='none', max_length=50, verbose_name='Dualblade Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_absolute_spear',
            field=models.BooleanField(default=False, verbose_name='Absolute Spear'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_disarm',
            field=models.BooleanField(default=False, verbose_name='Disarm'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_earthquake_stomp',
            field=models.BooleanField(default=False, verbose_name='Earthquake Stomp'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_frenzy',
            field=models.BooleanField(default=False, verbose_name='Frenzy'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_giant_stomp',
            field=models.BooleanField(default=False, verbose_name='Giant Stomp'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_infinity_strike',
            field=models.BooleanField(default=False, verbose_name='Infinity Strike'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_rolling_thunder',
            field=models.BooleanField(default=False, verbose_name='Rolling Thunder'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_vital_destruction',
            field=models.BooleanField(default=False, verbose_name='Vital Destruction'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='spear_weapon',
            field=models.CharField(choices=[('none', 'Other blue or lower'), ('body_slasher', 'Body Slasher'), ('lance', 'Lance'), ('archangel', 'Archangel Halberd'), ('tallum', 'Tallum Glaive'), ('halberd', 'Halberd'), ('saint', 'Saint Spear')], default='none', max_length=50, verbose_name='Spear Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_cancellation',
            field=models.BooleanField(default=False, verbose_name='Cancellation'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_chaos',
            field=models.BooleanField(default=False, verbose_name='Chaos'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_confuse',
            field=models.BooleanField(default=False, verbose_name='Confuse'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_frozen_crystal',
            field=models.BooleanField(default=False, verbose_name='Frozen Crystal'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_gravity',
            field=models.BooleanField(default=False, verbose_name='Gravity'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_meteor',
            field=models.BooleanField(default=False, verbose_name='Meteor'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_restore_casting',
            field=models.BooleanField(default=False, verbose_name='Restore Casting'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_snow_storm',
            field=models.BooleanField(default=False, verbose_name='Snow Storm'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='staff_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('daimon', 'Daimon Crystal'), ('stakato', "Stakato Queen's Staff"), ('archangel', 'Archangel Staff'), ('mother_tree', "Mother Tree's Branch"), ('spirits', "Spirits' Staff"), ('imperial', 'Imperial Staff')], default='none', max_length=50, verbose_name='Staff Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_brutal_attack',
            field=models.BooleanField(default=False, verbose_name='Brutal Attack'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_chain_strike',
            field=models.BooleanField(default=False, verbose_name='Chain Strike'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_double_shock',
            field=models.BooleanField(default=False, verbose_name='Double Shock'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_holy_strike',
            field=models.BooleanField(default=False, verbose_name='Holy Strike'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_iron_will',
            field=models.BooleanField(default=False, verbose_name='Iron Will'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_touch_of_life',
            field=models.BooleanField(default=False, verbose_name='Touch of Life'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_vengeance',
            field=models.BooleanField(default=False, verbose_name='Vengeance'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_vex',
            field=models.BooleanField(default=False, verbose_name='Vex'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='tank_weapon',
            field=models.CharField(choices=[('ssaurabi', 'Ssaurabi Long Sword'), ('none', 'Other blue or lower or none'), ('sirra', "Sirra's Blade"), ('archangel', 'Archangel Blade'), ('valhalla', 'Sword of Valhalla'), ('miracles', 'Sword of Miracles'), ('caladbolg', 'Caladbolg')], default='none', max_length=50, verbose_name='Tank Weapon'),
        ),
    ]
