# Generated by Django 5.2.7 on 2026-01-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_subclassstats_bow_absolute_piercing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclassstats',
            name='subclass_bonus_hp',
        ),
        migrations.RemoveField(
            model_name='subclassstats',
            name='subclass_bonus_mp',
        ),
        migrations.RemoveField(
            model_name='subclassstats',
            name='subclass_level',
        ),
    ]
