# Generated by Django 5.2.7 on 2026-01-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_remove_subclassstats_subclass_bonus_hp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusStats',
        ),
    ]
