# Generated by Django 5.2.7 on 2026-01-30 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_remove_bonusstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Dual Blades', 'Dual Blades'), ('Dagger', 'Dagger'), ('Orb', 'Orb'), ('Staff', 'Staff'), ('Bow', 'Bow'), ('One-handed sword', 'One-handed Sword'), ('Spear', 'Spear')], default='Spear', max_length=100, verbose_name='Kelas'),
        ),
    ]
