# Generated by Django 5.2.7 on 2026-01-31 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_character_owner_alter_character_character_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, help_text='Unique ID dari Discord/System', max_length=50, unique=True, verbose_name='Event ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Event')),
                ('event_type', models.CharField(choices=[('INVASION', 'Invasion'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs')], max_length=20, verbose_name='Tipe Event')),
                ('date', models.DateTimeField(verbose_name='Waktu Event')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Selesai')),
                ('is_win', models.BooleanField(default=False, help_text='Untuk Boss Rush & Catacombs', verbose_name='Menang')),
                ('bosses_killed', models.JSONField(blank=True, default=dict, help_text="Format: {'dragon_beast': true, 'carnifex': true, 'orfen': false}", verbose_name='Boss Terbunuh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Tanggal bulan (hari=1)', verbose_name='Bulan')),
                ('total_events', models.IntegerField(default=0, verbose_name='Total Event')),
                ('attended_events', models.IntegerField(default=0, verbose_name='Event Dihadiri')),
                ('attendance_rate', models.FloatField(default=0.0, verbose_name='Attendance Rate')),
                ('activity_score', models.IntegerField(default=0, verbose_name='Skor Aktivitas')),
                ('consistency_bonus', models.IntegerField(default=0, verbose_name='Bonus Konsistensi')),
                ('total_score', models.IntegerField(default=0, verbose_name='Total Skor')),
                ('tier', models.CharField(choices=[('ELITE', '🏆 Elite'), ('CORE', '⚔️ Core'), ('ACTIVE', '🛡️ Active'), ('CASUAL', '🌱 Casual')], default='CASUAL', max_length=20, verbose_name='Tier')),
                ('is_qualified', models.BooleanField(default=False, verbose_name='Qualified untuk Reward')),
                ('prize_amount', models.IntegerField(default=0, verbose_name='Jumlah Hadiah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='items.character', verbose_name='Karakter')),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'verbose_name_plural': 'Monthly Reports',
                'ordering': ['-month', '-total_score'],
                'unique_together': {('month', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.CharField(blank=True, help_text='Untuk mapping jika check-in via Discord', max_length=50, verbose_name='Discord User ID')),
                ('status', models.CharField(choices=[('ATTENDED', 'Hadir'), ('ABSENT', 'Tidak Hadir')], default='ATTENDED', max_length=20, verbose_name='Status')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Poin Didapat')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Check-In')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='items.activityevent', verbose_name='Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='items.character', verbose_name='Karakter')),
            ],
            options={
                'verbose_name': 'Player Activity',
                'verbose_name_plural': 'Player Activities',
                'ordering': ['-event__date'],
                'unique_together': {('player', 'event')},
            },
        ),
    ]
