# Generated by Django 5.2.7 on 2026-01-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_activityevent_monthlyreport_playeractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='discord_id',
            field=models.CharField(blank=True, help_text='ID Discord user yang di-link ke karakter ini. Format: 18-digit number.', max_length=50, null=True, unique=True, verbose_name='Discord ID'),
        ),
    ]
