# Generated by Django 5.2.7 on 2026-02-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_add_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeractivity',
            name='bosses_killed',
            field=models.JSONField(blank=True, default=dict, help_text="Spesifik untuk player ini: {'dragon_beast': true, 'carnifex': false, ...}", verbose_name='Boss Terbunuh (Individual)'),
        ),
    ]
