# Generated by Django 5.2.7 on 2026-02-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_playeractivity_bosses_killed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizePoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pool', models.IntegerField(default=10000, verbose_name='Total Prize Pool')),
                ('elite_percentage', models.FloatField(default=0.7, verbose_name='Elite %')),
                ('core_percentage', models.FloatField(default=0.2, verbose_name='Core %')),
                ('active_percentage', models.FloatField(default=0.1, verbose_name='Active %')),
                ('casual_percentage', models.FloatField(default=0.0, verbose_name='Casual %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Prize Pool Configuration',
                'verbose_name_plural': 'Prize Pool Configurations',
            },
        ),
    ]
