# Generated by Django 5.2.7 on 2026-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_prizepoolconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='core_percentage',
            field=models.FloatField(default=0.7, verbose_name='Core %'),
        ),
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='elite_percentage',
            field=models.FloatField(default=0.2, verbose_name='Elite %'),
        ),
    ]
