# Generated by Django 5.2.7 on 2026-02-06 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_alter_prizepoolconfig_core_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Set True setelah verifikasi kehadiran', verbose_name='Finalized (Poin Dibagi)'),
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Centang jika valid hadir', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Selesai (Fisik)'),
        ),
        migrations.CreateModel(
            name='DecayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decay_exception', to='items.character')),
            ],
        ),
        migrations.CreateModel(
            name='DKPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='Jumlah')),
                ('reason', models.CharField(max_length=255, verbose_name='Alasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dkp_logs', to='items.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
