# Generated by Django 5.2.7 on 2026-02-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0030_activityevent_is_finalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='decay_penalty',
            field=models.IntegerField(default=0, verbose_name='Decay Penalty'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='manual_adjustment',
            field=models.IntegerField(default=0, verbose_name='Manual Adjustment'),
        ),
    ]
