# Generated by Django 5.2.7 on 2026-02-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_monthlyreport_decay_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dkplog',
            name='character',
        ),
        migrations.RemoveField(
            model_name='dkplog',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='DecayException',
        ),
        migrations.DeleteModel(
            name='DKPLog',
        ),
    ]
