# Generated by Django 5.2.7 on 2026-02-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_discordalarm_discordannouncement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['-date'], name='items_activ_date_538c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['is_completed', '-date'], name='items_activ_is_comp_5d81cc_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type', '-date'], name='items_activ_event_t_1874ba_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['month', 'tier'], name='items_month_month_c48539_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['-total_score'], name='items_month_total_s_5bbf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['player', 'month'], name='items_month_player__34c10d_idx'),
        ),
        migrations.AddIndex(
            model_name='playeractivity',
            index=models.Index(fields=['player', 'status'], name='items_playe_player__0200c6_idx'),
        ),
        migrations.AddIndex(
            model_name='playeractivity',
            index=models.Index(fields=['event', 'status'], name='items_playe_event_i_adcc9b_idx'),
        ),
    ]
