# Generated by Django 5.2.7 on 2026-02-12 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INVASION', 'Invasion'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs'), ('CUSTOM', 'Custom Event')], max_length=20, verbose_name='Tipe Event'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='soulshot_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Soulshot Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_conquer',
            field=models.IntegerField(default=0, help_text='Conquer level (max 13, multiplied by 10 in score)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Conquer'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_guardian',
            field=models.IntegerField(default=0, help_text='Guardian level (max 13, multiplied by 10 in score)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Guardian'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='valor_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Valor Level'),
        ),
    ]
