# Generated by Django 5.2.7 on 2026-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_alter_activityevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='custom_points',
            field=models.IntegerField(default=10, help_text='Poin untuk Custom Event (diisi admin)', verbose_name='Poin Custom Event'),
        ),
    ]
