# Generated by Django 5.2.7 on 2026-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_activityevent_custom_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('One-Handed Sword Skill', 'One-Handed Sword Skill'), ('Dual-Wield Skills', 'Dual-Wield Skills'), ('Dagger Skill', 'Dagger Skill'), ('Bow Skill', 'Bow Skill'), ('Staff Skill', 'Staff Skill'), ('Greatsword Skill', 'Greatsword Skill'), ('Crossbow Skill', 'Crossbow Skill'), ('Chainsword Skill', 'Chainsword Skill'), ('Rapier Skill', 'Rapier Skill'), ('Magic Cannon Skill', 'Magic Cannon Skill'), ('Spear Skill', 'Spear Skill'), ('Orb Skill', 'Orb Skill'), ('Dual Axe Skill', 'Dual Axe Skill'), ('Soul Breaker Skill', 'Soul Breaker Skill')], default='Spear Skill', max_length=100, verbose_name='Kelas'),
        ),
    ]
