# Generated by Django 5.2.7 on 2026-02-14 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_alter_characterattributes_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='weapon_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Weapon Enchant Level'),
        ),
    ]
