# Generated by Django 5.2.7 on 2026-02-14 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_characterattributes_weapon_enchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_belt_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Belt Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_belt',
            field=models.CharField(blank=True, choices=[('', 'No belt selected'), ('Blue', 'Blue'), ("Ekimus' Belt", "Ekimus' Belt"), ('Dragon Belt', 'Dragon Belt'), ("Tiat's Belt", "Tiat's Belt"), ("Eratone's Belt", "Eratone's Belt"), ("Lord's Authority", "Lord's Authority"), ("Maphr's Belt", "Maphr's Belt")], max_length=100, verbose_name='PvP Belt'),
        ),
    ]
