# Generated by Django 5.2.7 on 2026-02-14 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_characterattributes_pvp_belt_enchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_ring_left_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Ring (Left) Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_ring_right_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Ring (Right) Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_left',
            field=models.CharField(blank=True, choices=[('', 'No ring selected'), ('Ring of Blessing', 'Ring of Blessing'), ("Lilith's Ring", "Lilith's Ring"), ("Anakeem's Ring", "Anakeem's Ring"), ("Baium's Ring", "Baium's Ring"), ("Vereth's Ring", "Vereth's Ring"), ('Core Ring', 'Core Ring'), ("Queen Ant's Ring", "Queen Ant's Ring"), ('Ring of Passion', 'Ring of Passion'), ('Majestic Ring', 'Majestic Ring'), ("Forgotten Hero's Ring", "Forgotten Hero's Ring"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Left)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_right',
            field=models.CharField(blank=True, choices=[('', 'No ring selected'), ('Ring of Blessing', 'Ring of Blessing'), ("Lilith's Ring", "Lilith's Ring"), ("Anakeem's Ring", "Anakeem's Ring"), ("Baium's Ring", "Baium's Ring"), ("Vereth's Ring", "Vereth's Ring"), ('Core Ring', 'Core Ring'), ("Queen Ant's Ring", "Queen Ant's Ring"), ('Ring of Passion', 'Ring of Passion'), ('Majestic Ring', 'Majestic Ring'), ("Forgotten Hero's Ring", "Forgotten Hero's Ring"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Right)'),
        ),
    ]
