# Generated by Django 5.2.7 on 2026-02-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0041_characterattributes_pvp_ring_left_enchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_necklace_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Necklace Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_necklace',
            field=models.CharField(blank=True, choices=[('', 'No necklace selected'), ('Blue necklace', 'Blue necklace'), ('Necklace of Immortality', 'Necklace of Immortality'), ("Lilith's Soul Necklace", "Lilith's Soul Necklace"), ("Anakeem's Soul Necklace", "Anakeem's Soul Necklace"), ("Baium's Necklace", "Baium's Necklace"), ("Zaken's Necklace", "Zaken's Necklace"), ("Orfen's Necklace", "Orfen's Necklace"), ('Majestic Necklace', 'Majestic Necklace'), ('Apella Necklace', 'Apella Necklace'), ("Valakas' Necklace", "Valakas' Necklace"), ('Antharas Necklace', 'Antharas Necklace'), ("Lindvior's Necklace", "Lindvior's Necklace"), ('Archmage Necklace', 'Archmage Necklace')], max_length=100, verbose_name='PvP Necklace'),
        ),
    ]
