# Generated by Django 5.2.7 on 2026-02-14 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0042_characterattributes_pvp_necklace_enchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_boots_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Boots Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_cloak_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Cloak Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_gaiters_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Gaiters Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_gloves_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Gloves Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_helmet_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Helmet Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_sigil_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Sigil Enchant Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_top_armor_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Armor Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_boots',
            field=models.CharField(blank=True, choices=[('', 'No boots selected'), ('Blue Wolf Boots', 'Blue Wolf Boots'), ('Majestic Boots', 'Majestic Boots'), ('Boots of Nightmares', 'Boots of Nightmares'), ('Dark Crystal Boots', 'Dark Crystal Boots'), ("Tersi's Boots", "Tersi's Boots"), ("Paulina's Boots", "Paulina's Boots"), ("Nevit's Boots", "Nevit's Boots"), ("Demon's Boots", "Demon's Boots"), ("Kaliel's Boots", "Kaliel's Boots"), ("Forgotten Hero's Boots", "Forgotten Hero's Boots"), ('Ancient Elven Boots', 'Ancient Elven Boots'), ('Draconic', 'Draconic'), ("Sayha's Wind", "Sayha's Wind")], max_length=100, verbose_name='PvP Boots'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_cloak',
            field=models.CharField(blank=True, choices=[('', 'No cloak selected'), ('Silver Cloak', 'Silver Cloak'), ("Cranigg's Cloak", "Cranigg's Cloak"), ("Dragon's Scale", "Dragon's Scale"), ("Zaken's Cloak", "Zaken's Cloak"), ('Cloak of Freya', 'Cloak of Freya'), ("Queen Ant's Wing", "Queen Ant's Wing"), ('Cloak of Silence', 'Cloak of Silence'), ('Eigis Cloak', 'Eigis Cloak'), ('Cloak of Authority', 'Cloak of Authority'), ("Selihoden's Wing", "Selihoden's Wing"), ("Nevit's Cloak of Light", "Nevit's Cloak of Light"), ("Nailop's Cloak", "Nailop's Cloak")], max_length=100, verbose_name='PvP Cloak'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gaiters',
            field=models.CharField(blank=True, choices=[('', 'No gaiters selected'), ('Blue Wolf Gaiters', 'Blue Wolf Gaiters'), ('Basila Skin', 'Basila Skin'), ('Blood Gaiters', 'Blood Gaiters'), ('Gaiters of Light', 'Gaiters of Light'), ('Gaiters of Ice', 'Gaiters of Ice'), ("Shilen's Breath", "Shilen's Breath"), ('Crystal Gaiters', 'Crystal Gaiters'), ("Forgotten Hero's Gaiters", "Forgotten Hero's Gaiters"), ('Imperial Crusader Gaiters', 'Imperial Crusader Gaiters')], max_length=100, verbose_name='PvP Gaiters'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gloves',
            field=models.CharField(blank=True, choices=[('', 'No gloves selected'), ('Blue Wolf Gloves', 'Blue Wolf Gloves'), ('Majestic Gloves', 'Majestic Gloves'), ('Gauntlets of Nightmare', 'Gauntlets of Nightmare'), ('Dark Crystal Gloves', 'Dark Crystal Gloves'), ("Tersi's Gloves", "Tersi's Gloves"), ("Paulina's Gauntlets", "Paulina's Gauntlets"), ("Nevit's Gloves", "Nevit's Gloves"), ('Jarngreipr', 'Jarngreipr'), ('Vision Guardian', 'Vision Guardian'), ('Gloves of Blessing', 'Gloves of Blessing'), ('Forgotten Hero Gloves', 'Forgotten Hero Gloves'), ("Demon's Gauntlets", "Demon's Gauntlets"), ('Ancient Elven Gauntlet', 'Ancient Elven Gauntlet'), ('Draconic Leather Gloves', 'Draconic Leather Gloves'), ("Pa'agrio's Flames", "Pa'agrio's Flames")], max_length=100, verbose_name='PvP Gloves'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_helmet',
            field=models.CharField(blank=True, choices=[('', 'No helmet selected'), ('Blue Wolf Helmet', 'Blue Wolf Helmet'), ('Majestic Circlet', 'Majestic Circlet'), ('Helm of Nightmares', 'Helm of Nightmares'), ('Dark Crystal Helmet', 'Dark Crystal Helmet'), ("Medusa's Helm", "Medusa's Helm"), ("Paulina's Helmet", "Paulina's Helmet"), ("Nevit's Helmet", "Nevit's Helmet"), ("Tersi's Circlet", "Tersi's Circlet"), ('Ancient Elven Helm', 'Ancient Elven Helm'), ('Imperial Crusader Helmet', 'Imperial Crusader Helmet'), ('Major Arcana Circlet', 'Major Arcana Circlet'), ('Draconic Helmet', 'Draconic Helmet')], max_length=100, verbose_name='PvP Helmet'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_sigil',
            field=models.CharField(blank=True, choices=[('', 'No sigil selected'), ('Dream Sigil', 'Dream Sigil'), ('Blue', 'Blue'), ("Susceptor's Heart", "Susceptor's Heart"), ("Paradia's Sigil", "Paradia's Sigil"), ("Cruma's Shell", "Cruma's Shell"), ('Sigil of Flames', 'Sigil of Flames'), ("Jaeger's Sigil", "Jaeger's Sigil"), ("Selihoden's Horn", "Selihoden's Horn"), ('Tear of Darkness', 'Tear of Darkness'), ('Draconic Sigil', 'Draconic Sigil'), ('Arcana Sigil', 'Arcana Sigil')], max_length=100, verbose_name='PvP Sigil'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_top_armor',
            field=models.CharField(blank=True, choices=[('', 'No armor selected'), ('Blue Wolf Breastplate', 'Blue Wolf Breastplate'), ('Majestic Robe', 'Majestic Robe'), ('Armor of Nightmares', 'Armor of Nightmares'), ('Dark Crystal Breastplate', 'Dark Crystal Breastplate'), ("Tersi's Robe", "Tersi's Robe"), ("Paulina's Breastplate", "Paulina's Breastplate"), ("Nevit's Armor", "Nevit's Armor"), ("Savan's Robe", "Savan's Robe"), ('Absolute Tunic', 'Absolute Tunic'), ('Apella Plate Armor', 'Apella Plate Armor'), ("Forgotten Hero's Breastplate", "Forgotten Hero's Breastplate"), ('Ancient Elven Armor', 'Ancient Elven Armor'), ("Demon's Armor", "Demon's Armor"), ('Draconic Leather Armor', 'Draconic Leather Armor'), ('Major Arcana Robe', 'Major Arcana Robe'), ('Imperial Crusader Breastplate', 'Imperial Crusader Breastplate')], max_length=100, verbose_name='PvP Top Armor'),
        ),
    ]
