# Generated by Django 5.2.7 on 2026-02-14 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0043_characterattributes_pvp_boots_enchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterattributes',
            name='soulshot_level',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Soulshot Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_conquer',
            field=models.IntegerField(blank=True, default=0, help_text='Conquer level (max 13, multiplied by 10 in score)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Conquer'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_guardian',
            field=models.IntegerField(blank=True, default=0, help_text='Guardian level (max 13, multiplied by 10 in score)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Guardian'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='valor_level',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Valor Level'),
        ),
    ]
