# Generated by Django 5.2.7 on 2026-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0044_alter_characterattributes_soulshot_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='carnifex_points',
            field=models.IntegerField(default=15, help_text='Poin bonus jika Carnifex terbunuh', verbose_name='Poin Carnifex'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='dragon_beast_points',
            field=models.IntegerField(default=10, help_text='Poin bonus jika Dragon Beast terbunuh', verbose_name='Poin Dragon Beast'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='orfen_points',
            field=models.IntegerField(default=25, help_text='Poin bonus jika Orfen terbunuh', verbose_name='Poin Orfen'),
        ),
    ]
