# Generated by Django 5.2.7 on 2026-02-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0045_activityevent_carnifex_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='exp_bow',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Bow Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_chainsword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Chainsword Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_crossbow',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Crossbow Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_dagger',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dagger Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_dual_axe',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual Axe Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_dual_wield',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual-Wield Skills'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_greatsword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Greatsword Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_magic_cannon',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Magic Cannon Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_one_handed_sword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='One-Handed Sword Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_orb',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Orb Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_rapier',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Rapier Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_soul_breaker',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Soul Breaker Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_spear',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Spear Skill'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='exp_staff',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Staff Skill'),
        ),
    ]
