# Generated by Django 5.2.7 on 2026-02-27 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0046_characterattributes_exp_bow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='aster_erafone',
            field=models.IntegerField(default=0, help_text='Maksimal 30 Node', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Aster'),
        ),
    ]
