# Generated by Django 5.2.7 on 2026-02-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0047_characterattributes_aster_erafone'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='total_epic_mount',
            field=models.IntegerField(default=0, help_text='Total Epic Mount (multiplied by 10 in score)', verbose_name='Total Epic Mount'),
        ),
    ]
