# Generated by Django 5.2.7 on 2026-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0048_characterattributes_total_epic_mount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_absolute_spear',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_disarm',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_earthquake_stomp',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_frenzy',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_giant_stomp',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_infinity_strike',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_rolling_thunder',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='skill_vital_destruction',
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='unlocked_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of unlocked skill names', verbose_name='Unlocked Skills'),
        ),
    ]
