# Generated by Django 5.2.7 on 2026-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0049_remove_characterattributes_skill_absolute_spear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendaryMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('icon_file', models.CharField(blank=True, max_length=100, verbose_name='File Ikon')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='legendary_mounts',
            field=models.ManyToManyField(blank=True, to='items.legendarymount', verbose_name='Mount Legendaris'),
        ),
    ]
