# Generated by Django 5.2.7 on 2026-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0050_legendarymount_character_legendary_mounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('icon_file', models.CharField(blank=True, max_length=100, verbose_name='File Ikon')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='mythic_classes',
            field=models.ManyToManyField(blank=True, to='items.mythicclass', verbose_name='Kelas Mythic'),
        ),
    ]
