# Generated by Django 5.2.7 on 2026-02-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0051_mythicclass_character_mythic_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_tshirt',
            field=models.CharField(blank=True, choices=[('', 'No t-shirt selected'), ("Agility's Anonymous Shirt", "Agility's Anonymous Shirt"), ('Anonymous Shirt of Knowledge', 'Anonymous Shirt of Knowledge'), ('Anonymous Shirt of Strength', 'Anonymous Shirt of Strength'), ('Focus Shirt', 'Focus Shirt'), ('Mithril Shirt of Agility', 'Mithril Shirt of Agility'), ('Mithril Shirt of Knowledge', 'Mithril Shirt of Knowledge'), ('Mithril Shirt of Strength', 'Mithril Shirt of Strength'), ('Vigilante Shirt', 'Vigilante Shirt'), ("Warrior's T-shirt", "Warrior's T-shirt")], max_length=100, verbose_name='PvP T-Shirt'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='pvp_tshirt_enchant',
            field=models.IntegerField(default=0, help_text='Enchant level +0 to +11', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP T-Shirt Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_boots',
            field=models.CharField(blank=True, choices=[('', 'No boots selected'), ('Ancient Elven Boots', 'Ancient Elven Boots'), ('Boots of Eternal Life', 'Boots of Eternal Life'), ('Boots of the Forgotten Hero', 'Boots of the Forgotten Hero'), ("Calie's Boots", "Calie's Boots"), ('Dark Crystal Boots', 'Dark Crystal Boots'), ("Devil's Boots", "Devil's Boots"), ('Draconic Leather Boots', 'Draconic Leather Boots'), ("Fallen Angel's Boots", "Fallen Angel's Boots"), ('Majestic Boots', 'Majestic Boots'), ("Nebit's Boots", "Nebit's Boots"), ('Nightmare Boots', 'Nightmare Boots'), ("Pauline's Boots", "Pauline's Boots"), ("Reaper's Boots", "Reaper's Boots"), ("Saiha's Wind", "Saiha's Wind"), ("Tersi's Boots", "Tersi's Boots")], max_length=100, verbose_name='PvP Boots'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_cloak',
            field=models.CharField(blank=True, choices=[('', 'No cloak selected'), ('Aegis Cloak', 'Aegis Cloak'), ('Cloak of Power', 'Cloak of Power'), ('Cloak of Silence', 'Cloak of Silence'), ('Cloak of Verdant Green', 'Cloak of Verdant Green'), ("Cranbel's Cloak", "Cranbel's Cloak"), ("Dragon's Scales", "Dragon's Scales"), ("Freya's Cloak", "Freya's Cloak"), ("Jaqen's Cloak", "Jaqen's Cloak"), ('Mantle of the Holy Spirit', 'Mantle of the Holy Spirit'), ("Moonlight's Cloak", "Moonlight's Cloak"), ("Nebit's Cloak of Light", "Nebit's Cloak of Light"), ("Niarop's Cloak", "Niarop's Cloak"), ("Salamander's Cloak", "Salamander's Cloak"), ("Sally Hoden's Wings", "Sally Hoden's Wings"), ('Queen Ant Wings', 'Queen Ant Wings')], max_length=100, verbose_name='PvP Cloak'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gaiters',
            field=models.CharField(blank=True, choices=[('', 'No gaiters selected'), ("Basil's Shell", "Basil's Shell"), ('Blood Greaves', 'Blood Greaves'), ("Blue Wolf's Leggings", "Blue Wolf's Leggings"), ('Breath of Silen', 'Breath of Silen'), ('Crystal Gaiters', 'Crystal Gaiters'), ("Devil's Pact", "Devil's Pact"), ("Fallen Angel's Legguards", "Fallen Angel's Legguards"), ('Flame Greaves', 'Flame Greaves'), ("Forgotten Hero's Greaves", "Forgotten Hero's Greaves"), ('Full Plate Gaiters', 'Full Plate Gaiters'), ('Ice Leggings', 'Ice Leggings'), ('Imperial Crusader Legguards', 'Imperial Crusader Legguards'), ("Light's Greaves", "Light's Greaves"), ('Patience Leggings', 'Patience Leggings'), ("Spirit's Greaves", "Spirit's Greaves")], max_length=100, verbose_name='PvP Gaiters'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gloves',
            field=models.CharField(blank=True, choices=[('', 'No gloves selected'), ('Ancient Elven Gauntlets', 'Ancient Elven Gauntlets'), ('Dark Crystal Globe', 'Dark Crystal Globe'), ("Devil's Gauntlet", "Devil's Gauntlet"), ('Draconic Leather Gloves', 'Draconic Leather Gloves'), ("Fallen Angel's Gloves", "Fallen Angel's Gloves"), ('Globe of the Forgotten Hero', 'Globe of the Forgotten Hero'), ('Gloves of Blessing', 'Gloves of Blessing'), ('Guardian of Vision', 'Guardian of Vision'), ('Jarngreifr', 'Jarngreifr'), ('Majestic Gloves', 'Majestic Gloves'), ("Nebit's Globe", "Nebit's Globe"), ('Nightmare Gauntlet', 'Nightmare Gauntlet'), ("Paagrio's Flame", "Paagrio's Flame"), ("Pauline's Gauntlet", "Pauline's Gauntlet"), ("Tersi's Gloves", "Tersi's Gloves")], max_length=100, verbose_name='PvP Gloves'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_helmet',
            field=models.CharField(blank=True, choices=[('', 'No helmet selected'), ('Ancient Elven Helmet', 'Ancient Elven Helmet'), ('Crown of the World Tree', 'Crown of the World Tree'), ('Dark Crystal Helmet', 'Dark Crystal Helmet'), ("Devil's Helmet", "Devil's Helmet"), ('Draconic Leather Helmet', 'Draconic Leather Helmet'), ('Helmet of the Fallen Angel', 'Helmet of the Fallen Angel'), ('Hildegrim', 'Hildegrim'), ('Imperial Crusader Helmet', 'Imperial Crusader Helmet'), ('Majestic Circlet', 'Majestic Circlet'), ('Major Arcana Circlet', 'Major Arcana Circlet'), ("Medusa's Helmet", "Medusa's Helmet"), ("Nebit's Helmet", "Nebit's Helmet"), ('Nightmare Helmet', 'Nightmare Helmet'), ("Pauline's Helmet", "Pauline's Helmet"), ("Tersi's Circlet", "Tersi's Circlet")], max_length=100, verbose_name='PvP Helmet'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_sigil',
            field=models.CharField(blank=True, choices=[('', 'No sigil selected'), ('Arcana Sigil', 'Arcana Sigil'), ('Blood Crystal', 'Blood Crystal'), ("Cruma's Shell", "Cruma's Shell"), ('Crystal of Oblivion', 'Crystal of Oblivion'), ('Draconic Sigil', 'Draconic Sigil'), ('Dream Sigil', 'Dream Sigil'), ('Eldarach', 'Eldarach'), ('Holy Sigil', 'Holy Sigil'), ('Parody Sigil', 'Parody Sigil'), ("Sally Horden's Horn", "Sally Horden's Horn"), ('Sniper Sigil', 'Sniper Sigil'), ("Susceptor's Heart", "Susceptor's Heart"), ('The Sigil of the Fallen Angel', 'The Sigil of the Fallen Angel'), ('The Sigil of Karma', 'The Sigil of Karma'), ('Tier of Darkness', 'Tier of Darkness')], max_length=100, verbose_name='PvP Sigil'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_top_armor',
            field=models.CharField(blank=True, choices=[('', 'No armor selected'), ('Absolute Tunic', 'Absolute Tunic'), ("Apella's Armor", "Apella's Armor"), ('Breastplate of the Fallen Angel', 'Breastplate of the Fallen Angel'), ('Breastplate of the Forgotten Hero', 'Breastplate of the Forgotten Hero'), ('Dark Crystal Breastplate', 'Dark Crystal Breastplate'), ("Devil's Armor", "Devil's Armor"), ('Draconic Leather Armor', 'Draconic Leather Armor'), ('Imperial Crusader Breastplate', 'Imperial Crusader Breastplate'), ('Majestic Robe', 'Majestic Robe'), ('Major Arcana Robe', 'Major Arcana Robe'), ("Nebit's Armor", "Nebit's Armor"), ('Nightmare Armor', 'Nightmare Armor'), ("Polyne's Breastplate", "Polyne's Breastplate"), ("Saban's Robe", "Saban's Robe"), ("Tersi's Robe", "Tersi's Robe")], max_length=100, verbose_name='PvP Top Armor'),
        ),
    ]
