# Generated by Django 5.2.7 on 2026-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0052_characterattributes_pvp_tshirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_assemble',
            field=models.BooleanField(default=False, verbose_name='Assemble'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_barrier_shot',
            field=models.BooleanField(default=False, verbose_name='Barrier Shot'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_blast_bomb',
            field=models.BooleanField(default=False, verbose_name='Blast Bomb II'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_canon_expansion',
            field=models.BooleanField(default=False, verbose_name='Canon Expansion'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_canon_night',
            field=models.BooleanField(default=False, verbose_name='Canon Night'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_enchant_aiming',
            field=models.BooleanField(default=False, verbose_name='Enchant Aiming'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_magic_trace',
            field=models.BooleanField(default=False, verbose_name='Magic Trace'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_slip',
            field=models.BooleanField(default=False, verbose_name='Slip'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='cannon_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('spirit_cannon', 'Spirit Cannon'), ('archangel', 'Archangel Cannon'), ('dark_cannon', 'Dark Cannon'), ('thunder_cannon', 'Thunder Cannon'), ('demon_cannon', 'Demon Cannon')], default='none', max_length=50, verbose_name='Magic Cannon Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_binding',
            field=models.BooleanField(default=False, verbose_name='Binding'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_bloody_slash',
            field=models.BooleanField(default=False, verbose_name='Bloody Slash II'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_bloody_sword',
            field=models.BooleanField(default=False, verbose_name='Bloody Sword'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_chain_chasing',
            field=models.BooleanField(default=False, verbose_name='Chain Chasing'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_chain_galaxy',
            field=models.BooleanField(default=False, verbose_name='Chain Galaxy'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_double_whip',
            field=models.BooleanField(default=False, verbose_name='Double Whip'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_overflow',
            field=models.BooleanField(default=False, verbose_name='Overflow'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_rust',
            field=models.BooleanField(default=False, verbose_name='Rust'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='chainsword_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('chain_hydra', 'Chain Hydra'), ('archangel', 'Archangel Chain'), ('viper_chain', 'Viper Chain'), ('bloody_chain', 'Bloody Chain'), ('demon_chain', 'Demon Chain')], default='none', max_length=50, verbose_name='Chainsword Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_back_tumbling',
            field=models.BooleanField(default=False, verbose_name='Back Tumbling'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_blackout_bolt',
            field=models.BooleanField(default=False, verbose_name='Blackout Bolt Shot'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_chain_bolt',
            field=models.BooleanField(default=False, verbose_name='Chain Bolt'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_disciplin',
            field=models.BooleanField(default=False, verbose_name='Disciplin'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_escape',
            field=models.BooleanField(default=False, verbose_name='Escape'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_feralize',
            field=models.BooleanField(default=False, verbose_name='Feralize'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_heroic_change',
            field=models.BooleanField(default=False, verbose_name='Heroic Change'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_vampiric_mind',
            field=models.BooleanField(default=False, verbose_name='Vampiric Mind'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='crossbow_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('arbalester', 'Arbalester'), ('archangel', 'Archangel Shooter'), ('ballista', 'Ballista'), ('death_trigger', 'Death Trigger'), ('evil_spirit', 'Evil Spirit Crossbow')], default='none', max_length=50, verbose_name='Crossbow Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_armor_break',
            field=models.BooleanField(default=False, verbose_name='Armor Break'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_berserk_fury',
            field=models.BooleanField(default=False, verbose_name='Berserk Fury'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_blood_rage',
            field=models.BooleanField(default=False, verbose_name='Blood Rage'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_cyclone',
            field=models.BooleanField(default=False, verbose_name='Cyclone'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_execute',
            field=models.BooleanField(default=False, verbose_name='Execute'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_power_crush',
            field=models.BooleanField(default=False, verbose_name='Power Crush'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_rage_strike',
            field=models.BooleanField(default=False, verbose_name='Rage Strike'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('twin_edge', 'Twin Edge'), ('archangel', 'Archangel Dual Axe'), ('destroyer', 'Destroyer'), ('blood_axes', 'Blood Axes'), ('doom_axes', 'Doom Axes')], default='none', max_length=50, verbose_name='Dual Axe Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='dualaxe_whirlwind',
            field=models.BooleanField(default=False, verbose_name='Whirlwind'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_bash',
            field=models.BooleanField(default=False, verbose_name='Bash III'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_crescendo_vitality',
            field=models.BooleanField(default=False, verbose_name='Crescendo Vitality'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_guardian_shield',
            field=models.BooleanField(default=False, verbose_name='Guardian Shield'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_hellfire',
            field=models.BooleanField(default=False, verbose_name='Hellfire'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_quake',
            field=models.BooleanField(default=False, verbose_name='Quake'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_reflect_stun',
            field=models.BooleanField(default=False, verbose_name='Reflect Stun'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_war_rage',
            field=models.BooleanField(default=False, verbose_name='War Rage'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_wave_sword',
            field=models.BooleanField(default=False, verbose_name='Wave Sword'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='greatsword_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('berserker_blade', 'Berserker Blade'), ('archangel', 'Archangel Slasher'), ('doom_crusher', 'Doom Crusher'), ('dragon_slayer', 'Dragon Slayer'), ('black_ore', 'Black Ore Greatsword')], default='none', max_length=50, verbose_name='Greatsword Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_arcane_shield',
            field=models.BooleanField(default=False, verbose_name='Arcane Shield'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_divine_execution',
            field=models.BooleanField(default=False, verbose_name='Divine Execution'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_divine_spark',
            field=models.BooleanField(default=False, verbose_name='Divine Spark'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_holy_light',
            field=models.BooleanField(default=False, verbose_name='Holy Light'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_improved_orb',
            field=models.BooleanField(default=False, verbose_name='Improved Orb'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_judgment',
            field=models.BooleanField(default=False, verbose_name='Judgment'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_last_hill',
            field=models.BooleanField(default=False, verbose_name='Last Hill'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_mess_hill',
            field=models.BooleanField(default=False, verbose_name='Mess Hill'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='orb_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('holy_orb', 'Holy Orb'), ('archangel', 'Archangel Orb'), ('spirit_orb', 'Spirit Orb'), ('divine_orb', 'Divine Orb'), ('celestial_orb', 'Celestial Orb')], default='none', max_length=50, verbose_name='Orb Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_black_feather',
            field=models.BooleanField(default=False, verbose_name='Black Feather'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_feather_pool',
            field=models.BooleanField(default=False, verbose_name='Feather Pool'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_parrying_arrow',
            field=models.BooleanField(default=False, verbose_name='Parrying Arrow'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_shooting_star',
            field=models.BooleanField(default=False, verbose_name='Shooting Star'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_sting',
            field=models.BooleanField(default=False, verbose_name='Sting III'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_summon_sword',
            field=models.BooleanField(default=False, verbose_name='Summon Sword'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_sword_blossom',
            field=models.BooleanField(default=False, verbose_name='Sword Blossom'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_traceless',
            field=models.BooleanField(default=False, verbose_name='Traceless'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='rapier_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('needle_rapier', 'Needle Rapier'), ('archangel', 'Archangel Rapier'), ('wind_rider', 'Wind Rider'), ('phantom_rapier', 'Phantom Rapier'), ('blood_rapier', 'Blood Rapier')], default='none', max_length=50, verbose_name='Rapier Weapon'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_annihilation',
            field=models.BooleanField(default=False, verbose_name='Annihilation'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_dark_blast',
            field=models.BooleanField(default=False, verbose_name='Dark Blast'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_dark_impulse',
            field=models.BooleanField(default=False, verbose_name='Dark Impulse'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_shadow_burst',
            field=models.BooleanField(default=False, verbose_name='Shadow Burst'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_soul_drain',
            field=models.BooleanField(default=False, verbose_name='Soul Drain'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_soul_shatter',
            field=models.BooleanField(default=False, verbose_name='Soul Shatter'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_soul_strike',
            field=models.BooleanField(default=False, verbose_name='Soul Strike'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_void_slash',
            field=models.BooleanField(default=False, verbose_name='Void Slash'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='soulbreaker_weapon',
            field=models.CharField(choices=[('none', 'Blue or lower or none'), ('soul_edge', 'Soul Edge'), ('archangel', 'Archangel Breaker'), ('dark_breaker', 'Dark Breaker'), ('phantom_breaker', 'Phantom Breaker'), ('chaos_breaker', 'Chaos Breaker')], default='none', max_length=50, verbose_name='Soul Breaker Weapon'),
        ),
    ]
