# Generated by Django 5.2.7 on 2026-02-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0053_subclassstats_cannon_assemble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclassstats',
            name='legend_skills',
            field=models.JSONField(blank=True, default=dict, help_text='Unlocked legend-tier skills per subclass', verbose_name='Legend Skills'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='myth_skills',
            field=models.JSONField(blank=True, default=dict, help_text='Unlocked myth-tier skills per subclass', verbose_name='Myth Skills'),
        ),
        migrations.AddField(
            model_name='subclassstats',
            name='subclass_weapons',
            field=models.JSONField(blank=True, default=dict, help_text='Selected weapon per subclass from weapon database', verbose_name='Subclass Weapons'),
        ),
    ]
