# Generated by Django 5.2.7 on 2026-03-01 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0055_remove_characteristicsstats_absolutvosthp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlyreport',
            name='items_month_month_c48539_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyreport',
            name='items_month_total_s_5bbf3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyreport',
            name='items_month_player__34c10d_idx',
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='manual_adjustment',
        ),
        migrations.RemoveField(
            model_name='playeractivity',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='balthazar_points',
            field=models.IntegerField(default=3, verbose_name='Balthazar Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='core_points',
            field=models.IntegerField(default=3, verbose_name='Core Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='kain_van_halter_points',
            field=models.IntegerField(default=3, verbose_name='Kain Van Halter Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='latana_points',
            field=models.IntegerField(default=2, verbose_name='Latana Points'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g1',
            field=models.IntegerField(default=0, verbose_name='Melee Damage Reduction'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g10',
            field=models.IntegerField(default=0, verbose_name='Max MP'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g11',
            field=models.IntegerField(default=0, verbose_name='Weapon Block (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g12',
            field=models.IntegerField(default=0, verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g13',
            field=models.IntegerField(default=0, verbose_name='Cooldown Reduction (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g14',
            field=models.IntegerField(default=0, verbose_name='Melee Damage'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g15',
            field=models.IntegerField(default=0, verbose_name='Melee Accuracy'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g16',
            field=models.IntegerField(default=0, verbose_name='Melee Critical Hit (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g17',
            field=models.IntegerField(default=0, verbose_name='Ranged Damage'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g18',
            field=models.IntegerField(default=0, verbose_name='Ranged Accuracy'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g19',
            field=models.IntegerField(default=0, verbose_name='Ranged Critical Hit (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g2',
            field=models.IntegerField(default=0, verbose_name='Ranged Damage Reduction'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g20',
            field=models.IntegerField(default=0, verbose_name='Magic Damage'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g21',
            field=models.IntegerField(default=0, verbose_name='Magic Accuracy'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g22',
            field=models.IntegerField(default=0, verbose_name='Magic Critical Hit (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g23',
            field=models.IntegerField(default=0, verbose_name='Weapon Damage Boost (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g24',
            field=models.IntegerField(default=0, verbose_name='Weapon Defense (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g25',
            field=models.IntegerField(default=0, verbose_name='Skill Damage Boost (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g26',
            field=models.IntegerField(default=0, verbose_name='Skill Defense (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g27',
            field=models.IntegerField(default=0, verbose_name='Attack Speed (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g28',
            field=models.IntegerField(default=0, verbose_name='Cast Speed (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g29',
            field=models.IntegerField(default=0, verbose_name='Weapon Damage'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g3',
            field=models.IntegerField(default=0, verbose_name='Magic Damage Reduction'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g30',
            field=models.IntegerField(default=0, verbose_name='Extra Damage'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g31',
            field=models.IntegerField(default=0, verbose_name='HP Recovery (Tick)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g32',
            field=models.IntegerField(default=0, verbose_name='MP Recovery (Tick)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g33',
            field=models.IntegerField(default=0, verbose_name='MP Consumption Reduction (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g34',
            field=models.IntegerField(default=0, verbose_name='Weight Limit'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g35',
            field=models.IntegerField(default=0, verbose_name='SOULSHOT Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g36',
            field=models.IntegerField(default=0, verbose_name='VALOR Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g37',
            field=models.IntegerField(default=0, verbose_name='GUARDIAN Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g38',
            field=models.IntegerField(default=0, verbose_name='CONQUER Level'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g4',
            field=models.IntegerField(default=0, verbose_name='Melee Evasion'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g5',
            field=models.IntegerField(default=0, verbose_name='Ranged Evasion'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g6',
            field=models.IntegerField(default=0, verbose_name='Magic Evasion'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g7',
            field=models.IntegerField(default=0, verbose_name='Skill Resistance'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g8',
            field=models.IntegerField(default=0, verbose_name='Movement Speed (%)'),
        ),
        migrations.AddField(
            model_name='characterattributes',
            name='g9',
            field=models.IntegerField(default=0, verbose_name='Max HP'),
        ),
        migrations.AddField(
            model_name='gearscorelog',
            name='characteristics_score',
            field=models.FloatField(default=0, verbose_name='Characteristics Score'),
        ),
        migrations.AddField(
            model_name='gearscorelog',
            name='gear_stats_score',
            field=models.FloatField(default=0, verbose_name='Gear Stats Score'),
        ),
        migrations.AddField(
            model_name='gearscorelog',
            name='mainclass_score',
            field=models.FloatField(default=0, verbose_name='Mainclass Score'),
        ),
        migrations.AddField(
            model_name='gearscorelog',
            name='subclass_score',
            field=models.FloatField(default=0, verbose_name='Subclass Score'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='carnifex_points',
            field=models.IntegerField(default=2, verbose_name='Carnifex Points'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='custom_points',
            field=models.IntegerField(blank=True, default=0, verbose_name='Custom Points'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='dragon_beast_points',
            field=models.IntegerField(default=2, verbose_name='Dragon Beast Points'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INVASION', 'Invasion'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs'), ('DIMENSIONAL_SIEGE', 'Dimensional Siege'), ('CUSTOM', 'Custom Event')], max_length=20, verbose_name='Tipe Event'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Selesai'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Finalized'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='orfen_points',
            field=models.IntegerField(default=2, verbose_name='Orfen Points'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_bow',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Bow Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_chainsword',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Chainsword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_crossbow',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Crossbow Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dagger',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dagger Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dual_axe',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual Axe Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dual_wield',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual-Wield Skills'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_greatsword',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Greatsword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_magic_cannon',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Magic Cannon Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_one_handed_sword',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='One-Handed Sword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_orb',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Orb Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_rapier',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Rapier Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_soul_breaker',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Soul Breaker Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_spear',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Spear Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_staff',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Staff Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_belt',
            field=models.CharField(blank=True, choices=[('Blue +3-4', 'Blue +3-4'), ('Blue +5+', 'Blue +5+'), ('Blue (other) and lower', 'Blue (other) and lower'), ("Ekimus' Belt +0", "Ekimus' Belt +0"), ("Ekimus' Belt +1-3", "Ekimus' Belt +1-3"), ("Ekimus' Belt +4+", "Ekimus' Belt +4+"), ('Dragon Belt +0', 'Dragon Belt +0'), ('Dragon Belt +1-3', 'Dragon Belt +1-3'), ('Dragon Belt +4+', 'Dragon Belt +4+'), ("Tiat's Belt +0", "Tiat's Belt +0"), ("Tiat's Belt +1-3", "Tiat's Belt +1-3"), ("Tiat's Belt +4+", "Tiat's Belt +4+"), ("Eratone's Belt +0", "Eratone's Belt +0"), ("Eratone's Belt +1-3", "Eratone's Belt +1-3"), ("Eratone's Belt +4+", "Eratone's Belt +4+"), ("Lord's Authority", "Lord's Authority"), ("Maphr's Belt", "Maphr's Belt")], max_length=100, verbose_name='PvP Belt'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_belt_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Belt Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_boots',
            field=models.CharField(blank=True, choices=[('Blue Wolf Boots +6+', 'Blue Wolf Boots +6+'), ('Other blue or lower', 'Other blue or lower'), ('Majestic Boots +5 or lower', 'Majestic Boots +5 or lower'), ('Majestic Boots +6+', 'Majestic Boots +6+'), ('Boots of Nightmares +5 or lower', 'Boots of Nightmares +5 or lower'), ('Boots of Nightmares +6+', 'Boots of Nightmares +6+'), ('Dark Crystal Boots +5 or lower', 'Dark Crystal Boots +5 or lower'), ('Dark Crystal Boots +6+', 'Dark Crystal Boots +6+'), ("Tersi's Boots +7 or lower", "Tersi's Boots +7 or lower"), ("Tersi's Boots +8+", "Tersi's Boots +8+"), ("Paulina's Boots +7 or lower", "Paulina's Boots +7 or lower"), ("Paulina's Boots +8+", "Paulina's Boots +8+"), ("Nevit's Boots +7 or lower", "Nevit's Boots +7 or lower"), ("Nevit's Boots +8+", "Nevit's Boots +8+"), ("Demon's Boots +5 or lower", "Demon's Boots +5 or lower"), ("Demon's Boots +6+", "Demon's Boots +6+"), ("Kaliel's Boots +7 or lower", "Kaliel's Boots +7 or lower"), ("Kaliel's Boots +8+", "Kaliel's Boots +8+"), ("Forgotten's Hero Boots +7 and lower", "Forgotten's Hero Boots +7 and lower"), ("Forgotten's Hero Boots +8+", "Forgotten's Hero Boots +8+"), ('Ancient Elven Boots +5 and lower', 'Ancient Elven Boots +5 and lower'), ('Ancient Elven Boots +6+', 'Ancient Elven Boots +6+'), ('Draconic', 'Draconic'), ("Sayha's Wind", "Sayha's Wind")], max_length=100, verbose_name='PvP Boots'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_boots_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Boots Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_cloak',
            field=models.CharField(blank=True, choices=[('Silver Cloak +7+', 'Silver Cloak +7+'), ("Cranigg's Cloak +6+", "Cranigg's Cloak +6+"), ('Other blue or green cloak', 'Other blue or green cloak'), ("Dragon's Scale +5 or lower", "Dragon's Scale +5 or lower"), ("Dragon's Scale +6+", "Dragon's Scale +6+"), ("Zaken's Cloak +5 or lower", "Zaken's Cloak +5 or lower"), ("Zaken's Cloak +6+", "Zaken's Cloak +6+"), ('Cloak of Freya +5 or lower', 'Cloak of Freya +5 or lower'), ('Cloak of Freya +6+', 'Cloak of Freya +6+'), ("Queen Ant's Wing +5 or lower", "Queen Ant's Wing +5 or lower"), ("Queen Ant's Wing +6+", "Queen Ant's Wing +6+"), ('Cloak of Silence +5 or lower', 'Cloak of Silence +5 or lower'), ('Cloak of Silence +6+', 'Cloak of Silence +6+'), ('Eigis Cloak +5 or lower', 'Eigis Cloak +5 or lower'), ('Eigis Cloak +6+', 'Eigis Cloak +6+'), ('Cloak of Authority +5 or lower', 'Cloak of Authority +5 or lower'), ('Cloak of Authority +6+', 'Cloak of Authority +6+'), ("Selihoden's Wing +5 and lower", "Selihoden's Wing +5 and lower"), ("Selihoden's Wing +6+", "Selihoden's Wing +6+"), ("Nevit's Cloak of Light", "Nevit's Cloak of Light"), ("Nailop's Cloak", "Nailop's Cloak")], max_length=100, verbose_name='PvP Cloak'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_cloak_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Cloak Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gaiters',
            field=models.CharField(blank=True, choices=[('Blue Wolf Gaiters +6+', 'Blue Wolf Gaiters +6+'), ('Basila Skin +6+', 'Basila Skin +6+'), ('Other blue or lower', 'Other blue or lower'), ('Blood Gaiters +5 and lower', 'Blood Gaiters +5 and lower'), ('Blood Gaiters +6+', 'Blood Gaiters +6+'), ('Gaiters of Light +5 and lower', 'Gaiters of Light +5 and lower'), ('Gaiters of Light +6+', 'Gaiters of Light +6+'), ('Gaiters of Ice +5 and lower', 'Gaiters of Ice +5 and lower'), ('Gaiters of Ice +6+', 'Gaiters of Ice +6+'), ("Shilen's Breath +5 and lower", "Shilen's Breath +5 and lower"), ("Shilen's Breath +6+", "Shilen's Breath +6+"), ('Crystal Gaiters +5 and lower', 'Crystal Gaiters +5 and lower'), ('Crystal Gaiters +6+', 'Crystal Gaiters +6+'), ("Forgotten Hero's Gaiters +5 and lower", "Forgotten Hero's Gaiters +5 and lower"), ("Forgotten Hero's Gaiters +6+", "Forgotten Hero's Gaiters +6+"), ('Imperial Crusader Gaiters', 'Imperial Crusader Gaiters')], max_length=100, verbose_name='PvP Gaiters'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gaiters_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Gaiters Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gloves',
            field=models.CharField(blank=True, choices=[('Blue Wolf Gloves +6+', 'Blue Wolf Gloves +6+'), ('Other blue or lower', 'Other blue or lower'), ('Majestic Gloves +5 and lower', 'Majestic Gloves +5 and lower'), ('Majestic Gloves +6+', 'Majestic Gloves +6+'), ('Gauntlets of Nightmare +5 and lower', 'Gauntlets of Nightmare +5 and lower'), ('Gauntlets of Nightmare +6+', 'Gauntlets of Nightmare +6+'), ('Dark Crystal Gloves +5 and lower', 'Dark Crystal Gloves +5 and lower'), ('Dark Crystal Gloves +6+', 'Dark Crystal Gloves +6+'), ("Tersi's Gloves +7 and lower", "Tersi's Gloves +7 and lower"), ("Tersi's Gloves +8+", "Tersi's Gloves +8+"), ("Paulina's Gauntlets +7 and lower", "Paulina's Gauntlets +7 and lower"), ("Paulina's Gauntlets +8+", "Paulina's Gauntlets +8+"), ("Nevit's Gloves +7 and lower", "Nevit's Gloves +7 and lower"), ("Nevit's Gloves +8+", "Nevit's Gloves +8+"), ('Jarngreipr +5 and lower', 'Jarngreipr +5 and lower'), ('Jarngreipr +6+', 'Jarngreipr +6+'), ('Vision Guardian +7 and lower', 'Vision Guardian +7 and lower'), ('Vision Guardian +8+', 'Vision Guardian +8+'), ('Gloves of Blessing +5 and lower', 'Gloves of Blessing +5 and lower'), ('Gloves of Blessing +6+', 'Gloves of Blessing +6+'), ('Forgotten Hero Gloves +7 and lower', 'Forgotten Hero Gloves +7 and lower'), ('Forgotten Hero Gloves +8+', 'Forgotten Hero Gloves +8+'), ("Demon's Gauntlets +5 and lower", "Demon's Gauntlets +5 and lower"), ("Demon's Gauntlets +6+", "Demon's Gauntlets +6+"), ('Ancient Elven Gauntlet +5 and lower', 'Ancient Elven Gauntlet +5 and lower'), ('Ancient Elven Gauntlet +6+', 'Ancient Elven Gauntlet +6+'), ('Draconic Leather Gloves', 'Draconic Leather Gloves'), ("Pa'agrio's Flames", "Pa'agrio's Flames")], max_length=100, verbose_name='PvP Gloves'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gloves_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Gloves Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_helmet',
            field=models.CharField(blank=True, choices=[('Blue Wolf Helmet +6+', 'Blue Wolf Helmet +6+'), ('Other blue or lower', 'Other blue or lower'), ('Majestic Circlet +5 and lower', 'Majestic Circlet +5 and lower'), ('Majestic Circlet +6+', 'Majestic Circlet +6+'), ('Helm of Nightmares +5 and lower', 'Helm of Nightmares +5 and lower'), ('Helm of Nightmares +6+', 'Helm of Nightmares +6+'), ('Dark Crystal Helmet +5 and lower', 'Dark Crystal Helmet +5 and lower'), ('Dark Crystal Helmet +6+', 'Dark Crystal Helmet +6+'), ("Medusa's Helm +5 and lower", "Medusa's Helm +5 and lower"), ("Medusa's Helm +6+", "Medusa's Helm +6+"), ("Paulina's Helmet +7 and lower", "Paulina's Helmet +7 and lower"), ("Paulina's Helmet +8+", "Paulina's Helmet +8+"), ("Nevit's Helmet +7 and lower", "Nevit's Helmet +7 and lower"), ("Nevit's Helmet +8+", "Nevit's Helmet +8+"), ("Tersi's Circlet +7 and lower", "Tersi's Circlet +7 and lower"), ("Tersi's Circlet +8+", "Tersi's Circlet +8+"), ('Ancient Elven Helm +5 and lower', 'Ancient Elven Helm +5 and lower'), ('Ancient Elven Helm +6+', 'Ancient Elven Helm +6+'), ('Imperial Crusader Helmet', 'Imperial Crusader Helmet'), ('Major Arcana Circlet', 'Major Arcana Circlet'), ('Draconic Helmet', 'Draconic Helmet')], max_length=100, verbose_name='PvP Helmet'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_helmet_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Helmet Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_necklace',
            field=models.CharField(blank=True, choices=[('Blue necklace +3-4', 'Blue necklace +3-4'), ('Blue necklace +5+', 'Blue necklace +5+'), ('Blue (other) and lower', 'Blue (other) and lower'), ('Necklace of Immortality +0', 'Necklace of Immortality +0'), ('Necklace of Immortality +1-3', 'Necklace of Immortality +1-3'), ('Necklace of Immortality +4+', 'Necklace of Immortality +4+'), ("Lilith's Soul Necklace +0", "Lilith's Soul Necklace +0"), ("Lilith's Soul Necklace +1-3", "Lilith's Soul Necklace +1-3"), ("Lilith's Soul Necklace +4+", "Lilith's Soul Necklace +4+"), ("Anakeem's Soul Necklace +0", "Anakeem's Soul Necklace +0"), ("Anakeem's Soul Necklace +1-3", "Anakeem's Soul Necklace +1-3"), ("Anakeem's Soul Necklace +4+", "Anakeem's Soul Necklace +4+"), ("Baium's Necklace +0", "Baium's Necklace +0"), ("Baium's Necklace +1-3", "Baium's Necklace +1-3"), ("Baium's Necklace +4+", "Baium's Necklace +4+"), ("Zaken's Necklace +0", "Zaken's Necklace +0"), ("Zaken's Necklace +1-3", "Zaken's Necklace +1-3"), ("Zaken's Necklace +4+", "Zaken's Necklace +4+"), ("Orfen's Necklace +0", "Orfen's Necklace +0"), ("Orfen's Necklace +1-3", "Orfen's Necklace +1-3"), ("Orfen's Necklace +4+", "Orfen's Necklace +4+"), ('Majestic Necklace +0', 'Majestic Necklace +0'), ('Majestic Necklace +1-3', 'Majestic Necklace +1-3'), ('Majestic Necklace +4+', 'Majestic Necklace +4+'), ('Apella Necklace +0', 'Apella Necklace +0'), ('Apella Necklace +1-3', 'Apella Necklace +1-3'), ('Apella Necklace +4+', 'Apella Necklace +4+'), ("Valakas' Necklace +0", "Valakas' Necklace +0"), ('Antharas Necklace +0', 'Antharas Necklace +0'), ("Lindvior's Necklace +0", "Lindvior's Necklace +0"), ('Archmage Necklace +0', 'Archmage Necklace +0')], max_length=100, verbose_name='PvP Necklace'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_necklace_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Necklace Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_left',
            field=models.CharField(blank=True, choices=[('Ring of Blessing +3+', 'Ring of Blessing +3+'), ('Other blue or lower', 'Other blue or lower'), ("Lilith's Ring +0", "Lilith's Ring +0"), ("Lilith's Ring +1-3", "Lilith's Ring +1-3"), ("Lilith's Ring +4+", "Lilith's Ring +4+"), ("Anakeem's Ring +0", "Anakeem's Ring +0"), ("Anakeem's Ring +1-3", "Anakeem's Ring +1-3"), ("Anakeem's Ring +4+", "Anakeem's Ring +4+"), ("Baium's Ring +0", "Baium's Ring +0"), ("Baium's Ring +1-3", "Baium's Ring +1-3"), ("Baium's Ring +4+", "Baium's Ring +4+"), ("Vereth's Ring +0", "Vereth's Ring +0"), ("Vereth's Ring +1-3", "Vereth's Ring +1-3"), ("Vereth's Ring +4+", "Vereth's Ring +4+"), ('Core Ring +0', 'Core Ring +0'), ('Core Ring +1-3', 'Core Ring +1-3'), ('Core Ring +4+', 'Core Ring +4+'), ("Queen Ant's Ring +0", "Queen Ant's Ring +0"), ("Queen Ant's Ring +1-3", "Queen Ant's Ring +1-3"), ("Queen Ant's Ring +4+", "Queen Ant's Ring +4+"), ('Ring of Passion +0', 'Ring of Passion +0'), ('Ring of Passion +1-3', 'Ring of Passion +1-3'), ('Ring of Passion +4+', 'Ring of Passion +4+'), ('Majestic Ring +0', 'Majestic Ring +0'), ('Majestic Ring +1-3', 'Majestic Ring +1-3'), ('Majestic Ring +4+', 'Majestic Ring +4+'), ("Forgotten Hero's Ring +0", "Forgotten Hero's Ring +0"), ("Forgotten Hero's Ring +1-3", "Forgotten Hero's Ring +1-3"), ("Forgotten Hero's Ring +4+", "Forgotten Hero's Ring +4+"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Left)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_left_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Ring (Left) Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_right',
            field=models.CharField(blank=True, choices=[('Ring of Blessing +3+', 'Ring of Blessing +3+'), ('Other blue or lower', 'Other blue or lower'), ("Lilith's Ring +0", "Lilith's Ring +0"), ("Lilith's Ring +1-3", "Lilith's Ring +1-3"), ("Lilith's Ring +4+", "Lilith's Ring +4+"), ("Anakeem's Ring +0", "Anakeem's Ring +0"), ("Anakeem's Ring +1-3", "Anakeem's Ring +1-3"), ("Anakeem's Ring +4+", "Anakeem's Ring +4+"), ("Baium's Ring +0", "Baium's Ring +0"), ("Baium's Ring +1-3", "Baium's Ring +1-3"), ("Baium's Ring +4+", "Baium's Ring +4+"), ("Vereth's Ring +0", "Vereth's Ring +0"), ("Vereth's Ring +1-3", "Vereth's Ring +1-3"), ("Vereth's Ring +4+", "Vereth's Ring +4+"), ('Core Ring +0', 'Core Ring +0'), ('Core Ring +1-3', 'Core Ring +1-3'), ('Core Ring +4+', 'Core Ring +4+'), ("Queen Ant's Ring +0", "Queen Ant's Ring +0"), ("Queen Ant's Ring +1-3", "Queen Ant's Ring +1-3"), ("Queen Ant's Ring +4+", "Queen Ant's Ring +4+"), ('Ring of Passion +0', 'Ring of Passion +0'), ('Ring of Passion +1-3', 'Ring of Passion +1-3'), ('Ring of Passion +4+', 'Ring of Passion +4+'), ('Majestic Ring +0', 'Majestic Ring +0'), ('Majestic Ring +1-3', 'Majestic Ring +1-3'), ('Majestic Ring +4+', 'Majestic Ring +4+'), ("Forgotten Hero's Ring +0", "Forgotten Hero's Ring +0"), ("Forgotten Hero's Ring +1-3", "Forgotten Hero's Ring +1-3"), ("Forgotten Hero's Ring +4+", "Forgotten Hero's Ring +4+"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Right)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_right_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Ring (Right) Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_sigil',
            field=models.CharField(blank=True, choices=[('Dream Sigil +3-4', 'Dream Sigil +3-4'), ('Dream Sigil +5+', 'Dream Sigil +5+'), ('Blue (other) and lower', 'Blue (other) and lower'), ("Susceptor's Heart +0", "Susceptor's Heart +0"), ("Susceptor's Heart +1-3", "Susceptor's Heart +1-3"), ("Susceptor's Heart +4+", "Susceptor's Heart +4+"), ("Paradia's Sigil +0", "Paradia's Sigil +0"), ("Paradia's Sigil +1-3", "Paradia's Sigil +1-3"), ("Paradia's Sigil +4+", "Paradia's Sigil +4+"), ("Cruma's Shell +0", "Cruma's Shell +0"), ("Cruma's Shell +1-3", "Cruma's Shell +1-3"), ("Cruma's Shell +4+", "Cruma's Shell +4+"), ('Sigil of Flames +0', 'Sigil of Flames +0'), ('Sigil of Flames +1-3', 'Sigil of Flames +1-3'), ('Sigil of Flames +4+', 'Sigil of Flames +4+'), ("Jaeger's Sigil +0", "Jaeger's Sigil +0"), ("Jaeger's Sigil +1-3", "Jaeger's Sigil +1-3"), ("Jaeger's Sigil +4+", "Jaeger's Sigil +4+"), ("Selihoden's Horn +0", "Selihoden's Horn +0"), ("Selihoden's Horn +1-3", "Selihoden's Horn +1-3"), ("Selihoden's Horn +4+", "Selihoden's Horn +4+"), ('Tear of Darkness', 'Tear of Darkness'), ('Draconic Sigil', 'Draconic Sigil'), ('Arcana Sigil', 'Arcana Sigil')], max_length=100, verbose_name='PvP Sigil'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_sigil_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Sigil Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_top_armor',
            field=models.CharField(blank=True, choices=[('Blue Wolf Breastplate +6+', 'Blue Wolf Breastplate +6+'), ('Other blue or lower', 'Other blue or lower'), ('Majestic Robe +5 and lower', 'Majestic Robe +5 and lower'), ('Majestic Robe +6+', 'Majestic Robe +6+'), ('Armor of Nightmares +5 and lower', 'Armor of Nightmares +5 and lower'), ('Armor of Nightmares +6+', 'Armor of Nightmares +6+'), ('Dark Crystal Breastplate +5 and lower', 'Dark Crystal Breastplate +5 and lower'), ('Dark Crystal Breastplate +6+', 'Dark Crystal Breastplate +6+'), ("Tersi's Robe +7 and lower", "Tersi's Robe +7 and lower"), ("Tersi's Robe +8+", "Tersi's Robe +8+"), ("Paulina's Breastplate +7 and lower", "Paulina's Breastplate +7 and lower"), ("Paulina's Breastplate +8+", "Paulina's Breastplate +8+"), ("Nevit's Armor +7 and lower", "Nevit's Armor +7 and lower"), ("Nevit's Armor +8+", "Nevit's Armor +8+"), ("Savan's Robe +5 and lower", "Savan's Robe +5 and lower"), ("Savan's Robe +6+", "Savan's Robe +6+"), ('Absolute Tunic +5 and lower', 'Absolute Tunic +5 and lower'), ('Absolute Tunic +6+', 'Absolute Tunic +6+'), ('Apella Plate Armor +5 and lower', 'Apella Plate Armor +5 and lower'), ('Apella Plate Armor +6+', 'Apella Plate Armor +6+'), ("Forgotten Hero's Breastplate +7 and lower", "Forgotten Hero's Breastplate +7 and lower"), ("Forgotten Hero's Breastplate +8+", "Forgotten Hero's Breastplate +8+"), ('Ancient Elven Armor +5 and lower', 'Ancient Elven Armor +5 and lower'), ('Ancient Elven Armor +6+', 'Ancient Elven Armor +6+'), ("Demon's Armor +5 and lower", "Demon's Armor +5 and lower"), ("Demon's Armor +6+", "Demon's Armor +6+"), ('Draconic Leather Armor', 'Draconic Leather Armor'), ('Major Arcana Robe', 'Major Arcana Robe'), ('Imperial Crusader Breastplate', 'Imperial Crusader Breastplate')], max_length=100, verbose_name='PvP Top Armor'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_top_armor_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP Armor Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_tshirt',
            field=models.CharField(blank=True, choices=[('Blue or lower', 'Blue or lower'), ('Red T-Shirt +5 or lower', 'Red T-Shirt +5 or lower'), ('Red T-Shirt +6+', 'Red T-Shirt +6+'), ('Purple T-Shirt +5 or lower', 'Purple T-Shirt +5 or lower'), ('Purple T-Shirt +6+', 'Purple T-Shirt +6+')], max_length=100, verbose_name='PvP T-Shirt'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_tshirt_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='PvP T-Shirt Enchant Level'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_acc',
            field=models.IntegerField(default=0, verbose_name='ACC (Accuracy)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_conquer',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Conquer'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_def',
            field=models.IntegerField(default=0, verbose_name='DEF (Defense)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_dmg',
            field=models.IntegerField(default=0, verbose_name='DMG (Damage)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_guardian',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)], verbose_name='Guardian'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_reduc',
            field=models.IntegerField(default=0, verbose_name='REDUC (Damage Reduction)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_resist',
            field=models.IntegerField(default=0, verbose_name='RESIST (Resistance)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_skill_dmg_boost',
            field=models.IntegerField(default=0, verbose_name='Skill DMG Boost'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='stat_wpn_dmg_boost',
            field=models.IntegerField(default=0, verbose_name='Weapon DMG Boost'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='total_epic_mount',
            field=models.IntegerField(default=0, verbose_name='Total Epic Mount'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='total_legend_codex',
            field=models.IntegerField(default=0, verbose_name='Total Legend Codex'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='unlocked_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Unlocked Skills'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='weapon',
            field=models.CharField(blank=True, choices=[('', 'No weapon selected'), ('bow|Akatt Longbow', 'Akatt Longbow'), ('bow|Archangel Bow', 'Archangel Bow'), ('bow|Bow of Oblivion', 'Bow of Oblivion'), ('bow|Carnium Bow', 'Carnium Bow'), ('bow|Ice Crystal Bow', 'Ice Crystal Bow'), ('bow|Plasma Bow', 'Plasma Bow'), ('cane|Archangel Staff', 'Archangel Staff'), ('cane|Branch of Life', 'Branch of Life'), ('cane|Crystal Wand', 'Crystal Wand'), ('cane|Desperion Staff', 'Desperion Staff'), ('cane|Imperial Sttaff', 'Imperial Sttaff'), ('chainsword|Archangel Chainsword', 'Archangel Chainsword'), ('chainsword|Bultgang', 'Bultgang'), ('chainsword|Dragon Hunter', 'Dragon Hunter'), ('chainsword|Gram', 'Gram'), ('crossbow|Archangel Crossbow', 'Archangel Crossbow'), ('crossbow|Ballista', 'Ballista'), ('crossbow|Giant Crossbow', 'Giant Crossbow'), ('crossbow|Peacemaker', 'Peacemaker'), ('dagger|Archangel Slayer', 'Archangel Slayer'), ('dagger|Blood Orchid', 'Blood Orchid'), ('dagger|Crystal Dagger', 'Crystal Dagger'), ('dagger|Giant Dagger', 'Giant Dagger'), ('double_axe|Archangel Twin Axe', 'Archangel Twin Axe'), ('double_axe|Clarent', 'Clarent'), ('greatsword|Archangel Buster', 'Archangel Buster'), ('greatsword|Dragon Slayer', 'Dragon Slayer'), ('magic_cannon|Archangel Blaster', 'Archangel Blaster'), ('magic_cannon|Divine Blaster', 'Divine Blaster'), ('one_handed_sword|Archangel Blade', 'Archangel Blade'), ('one_handed_sword|Sword of Valhalla', 'Sword of Valhalla'), ('orb|Archangel Orb', 'Archangel Orb'), ('orb|Hand of Cabrio', 'Hand of Cabrio'), ('rapier|Archangel Rapier', 'Archangel Rapier'), ('rapier|Grid Rapier', 'Grid Rapier'), ('soul_breaker|Archangel Soul Breaker', 'Archangel Soul Breaker'), ('spear|Archangel Halberd', 'Archangel Halberd'), ('spear|Tallum Glaive', 'Tallum Glaive'), ('two_sword_style|Archangel Dual Swords', 'Archangel Dual Swords')], max_length=100, verbose_name='Weapon'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='weapon_enchant',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Weapon Enchant Level'),
        ),
        migrations.AlterField(
            model_name='gearscorelog',
            name='reason',
            field=models.CharField(default='Character update', max_length=255),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='discord_user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Discord User ID'),
        ),
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='core_percentage',
            field=models.FloatField(default=0.2, verbose_name='Core %'),
        ),
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='elite_percentage',
            field=models.FloatField(default=0.7, verbose_name='Elite %'),
        ),
    ]
