# Generated by Django 5.2.7 on 2026-03-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0056_remove_monthlyreport_items_month_month_c48539_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_bow',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Bow Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_chainsword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Chainsword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_crossbow',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Crossbow Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dagger',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dagger Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dual_axe',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual Axe Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_dual_wield',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Dual-Wield Skills'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_greatsword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Greatsword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_magic_cannon',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Magic Cannon Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_one_handed_sword',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='One-Handed Sword Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_orb',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Orb Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_rapier',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Rapier Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_soul_breaker',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Soul Breaker Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_spear',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Spear Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='exp_staff',
            field=models.IntegerField(blank=True, choices=[(0, 'No Expertise'), (1, 'Rank 1'), (2, 'Rank 2'), (3, 'Rank 3'), (4, 'Rank 4'), (5, 'Rank 5'), (6, 'Rank 6'), (7, 'Rank 7'), (8, 'Rank 8'), (9, 'Rank 9')], default=0, verbose_name='Staff Skill'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_belt',
            field=models.CharField(blank=True, choices=[('', 'No belt selected'), ('Blue', 'Blue'), ("Ekimus' Belt", "Ekimus' Belt"), ('Dragon Belt', 'Dragon Belt'), ("Tiat's Belt", "Tiat's Belt"), ("Eratone's Belt", "Eratone's Belt"), ("Lord's Authority", "Lord's Authority"), ("Maphr's Belt", "Maphr's Belt")], max_length=100, verbose_name='PvP Belt'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_boots',
            field=models.CharField(blank=True, choices=[('', 'No boots selected'), ('Ancient Elven Boots', 'Ancient Elven Boots'), ('Boots of Eternal Life', 'Boots of Eternal Life'), ('Boots of the Forgotten Hero', 'Boots of the Forgotten Hero'), ("Calie's Boots", "Calie's Boots"), ('Dark Crystal Boots', 'Dark Crystal Boots'), ("Devil's Boots", "Devil's Boots"), ('Draconic Leather Boots', 'Draconic Leather Boots'), ("Fallen Angel's Boots", "Fallen Angel's Boots"), ('Majestic Boots', 'Majestic Boots'), ("Nebit's Boots", "Nebit's Boots"), ('Nightmare Boots', 'Nightmare Boots'), ("Pauline's Boots", "Pauline's Boots"), ("Reaper's Boots", "Reaper's Boots"), ("Saiha's Wind", "Saiha's Wind"), ("Tersi's Boots", "Tersi's Boots")], max_length=100, verbose_name='PvP Boots'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_cloak',
            field=models.CharField(blank=True, choices=[('', 'No cloak selected'), ('Aegis Cloak', 'Aegis Cloak'), ('Cloak of Power', 'Cloak of Power'), ('Cloak of Silence', 'Cloak of Silence'), ('Cloak of Verdant Green', 'Cloak of Verdant Green'), ("Cranbel's Cloak", "Cranbel's Cloak"), ("Dragon's Scales", "Dragon's Scales"), ("Freya's Cloak", "Freya's Cloak"), ("Jaqen's Cloak", "Jaqen's Cloak"), ('Mantle of the Holy Spirit', 'Mantle of the Holy Spirit'), ("Moonlight's Cloak", "Moonlight's Cloak"), ("Nebit's Cloak of Light", "Nebit's Cloak of Light"), ("Niarop's Cloak", "Niarop's Cloak"), ("Salamander's Cloak", "Salamander's Cloak"), ("Sally Hoden's Wings", "Sally Hoden's Wings"), ('Queen Ant Wings', 'Queen Ant Wings')], max_length=100, verbose_name='PvP Cloak'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gaiters',
            field=models.CharField(blank=True, choices=[('', 'No gaiters selected'), ("Basil's Shell", "Basil's Shell"), ('Blood Greaves', 'Blood Greaves'), ("Blue Wolf's Leggings", "Blue Wolf's Leggings"), ('Breath of Silen', 'Breath of Silen'), ('Crystal Gaiters', 'Crystal Gaiters'), ("Devil's Pact", "Devil's Pact"), ("Fallen Angel's Legguards", "Fallen Angel's Legguards"), ('Flame Greaves', 'Flame Greaves'), ("Forgotten Hero's Greaves", "Forgotten Hero's Greaves"), ('Full Plate Gaiters', 'Full Plate Gaiters'), ('Ice Leggings', 'Ice Leggings'), ('Imperial Crusader Legguards', 'Imperial Crusader Legguards'), ("Light's Greaves", "Light's Greaves"), ('Patience Leggings', 'Patience Leggings'), ("Spirit's Greaves", "Spirit's Greaves")], max_length=100, verbose_name='PvP Gaiters'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_gloves',
            field=models.CharField(blank=True, choices=[('', 'No gloves selected'), ('Ancient Elven Gauntlets', 'Ancient Elven Gauntlets'), ('Dark Crystal Globe', 'Dark Crystal Globe'), ("Devil's Gauntlet", "Devil's Gauntlet"), ('Draconic Leather Gloves', 'Draconic Leather Gloves'), ("Fallen Angel's Gloves", "Fallen Angel's Gloves"), ('Globe of the Forgotten Hero', 'Globe of the Forgotten Hero'), ('Gloves of Blessing', 'Gloves of Blessing'), ('Guardian of Vision', 'Guardian of Vision'), ('Jarngreifr', 'Jarngreifr'), ('Majestic Gloves', 'Majestic Gloves'), ("Nebit's Globe", "Nebit's Globe"), ('Nightmare Gauntlet', 'Nightmare Gauntlet'), ("Paagrio's Flame", "Paagrio's Flame"), ("Pauline's Gauntlet", "Pauline's Gauntlet"), ("Tersi's Gloves", "Tersi's Gloves")], max_length=100, verbose_name='PvP Gloves'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_helmet',
            field=models.CharField(blank=True, choices=[('', 'No helmet selected'), ('Ancient Elven Helmet', 'Ancient Elven Helmet'), ('Crown of the World Tree', 'Crown of the World Tree'), ('Dark Crystal Helmet', 'Dark Crystal Helmet'), ("Devil's Helmet", "Devil's Helmet"), ('Draconic Leather Helmet', 'Draconic Leather Helmet'), ('Helmet of the Fallen Angel', 'Helmet of the Fallen Angel'), ('Hildegrim', 'Hildegrim'), ('Imperial Crusader Helmet', 'Imperial Crusader Helmet'), ('Majestic Circlet', 'Majestic Circlet'), ('Major Arcana Circlet', 'Major Arcana Circlet'), ("Medusa's Helmet", "Medusa's Helmet"), ("Nebit's Helmet", "Nebit's Helmet"), ('Nightmare Helmet', 'Nightmare Helmet'), ("Pauline's Helmet", "Pauline's Helmet"), ("Tersi's Circlet", "Tersi's Circlet")], max_length=100, verbose_name='PvP Helmet'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_necklace',
            field=models.CharField(blank=True, choices=[('', 'No necklace selected'), ('Blue necklace', 'Blue necklace'), ('Necklace of Immortality', 'Necklace of Immortality'), ("Lilith's Soul Necklace", "Lilith's Soul Necklace"), ("Anakeem's Soul Necklace", "Anakeem's Soul Necklace"), ("Baium's Necklace", "Baium's Necklace"), ("Zaken's Necklace", "Zaken's Necklace"), ("Orfen's Necklace", "Orfen's Necklace"), ('Majestic Necklace', 'Majestic Necklace'), ('Apella Necklace', 'Apella Necklace'), ("Valakas' Necklace", "Valakas' Necklace"), ('Antharas Necklace', 'Antharas Necklace'), ("Lindvior's Necklace", "Lindvior's Necklace"), ('Archmage Necklace', 'Archmage Necklace')], max_length=100, verbose_name='PvP Necklace'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_left',
            field=models.CharField(blank=True, choices=[('', 'No ring selected'), ('Ring of Blessing', 'Ring of Blessing'), ("Lilith's Ring", "Lilith's Ring"), ("Anakeem's Ring", "Anakeem's Ring"), ("Baium's Ring", "Baium's Ring"), ("Vereth's Ring", "Vereth's Ring"), ('Core Ring', 'Core Ring'), ("Queen Ant's Ring", "Queen Ant's Ring"), ('Ring of Passion', 'Ring of Passion'), ('Majestic Ring', 'Majestic Ring'), ("Forgotten Hero's Ring", "Forgotten Hero's Ring"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Left)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_ring_right',
            field=models.CharField(blank=True, choices=[('', 'No ring selected'), ('Ring of Blessing', 'Ring of Blessing'), ("Lilith's Ring", "Lilith's Ring"), ("Anakeem's Ring", "Anakeem's Ring"), ("Baium's Ring", "Baium's Ring"), ("Vereth's Ring", "Vereth's Ring"), ('Core Ring', 'Core Ring'), ("Queen Ant's Ring", "Queen Ant's Ring"), ('Ring of Passion', 'Ring of Passion'), ('Majestic Ring', 'Majestic Ring'), ("Forgotten Hero's Ring", "Forgotten Hero's Ring"), ("Desperion's Ring", "Desperion's Ring")], max_length=100, verbose_name='PvP Ring (Right)'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_sigil',
            field=models.CharField(blank=True, choices=[('', 'No sigil selected'), ('Arcana Sigil', 'Arcana Sigil'), ('Blood Crystal', 'Blood Crystal'), ("Cruma's Shell", "Cruma's Shell"), ('Crystal of Oblivion', 'Crystal of Oblivion'), ('Draconic Sigil', 'Draconic Sigil'), ('Dream Sigil', 'Dream Sigil'), ('Eldarach', 'Eldarach'), ('Holy Sigil', 'Holy Sigil'), ('Parody Sigil', 'Parody Sigil'), ("Sally Horden's Horn", "Sally Horden's Horn"), ('Sniper Sigil', 'Sniper Sigil'), ("Susceptor's Heart", "Susceptor's Heart"), ('The Sigil of the Fallen Angel', 'The Sigil of the Fallen Angel'), ('The Sigil of Karma', 'The Sigil of Karma'), ('Tier of Darkness', 'Tier of Darkness')], max_length=100, verbose_name='PvP Sigil'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_top_armor',
            field=models.CharField(blank=True, choices=[('', 'No armor selected'), ('Absolute Tunic', 'Absolute Tunic'), ("Apella's Armor", "Apella's Armor"), ('Breastplate of the Fallen Angel', 'Breastplate of the Fallen Angel'), ('Breastplate of the Forgotten Hero', 'Breastplate of the Forgotten Hero'), ('Dark Crystal Breastplate', 'Dark Crystal Breastplate'), ("Devil's Armor", "Devil's Armor"), ('Draconic Leather Armor', 'Draconic Leather Armor'), ('Imperial Crusader Breastplate', 'Imperial Crusader Breastplate'), ('Majestic Robe', 'Majestic Robe'), ('Major Arcana Robe', 'Major Arcana Robe'), ("Nebit's Armor", "Nebit's Armor"), ('Nightmare Armor', 'Nightmare Armor'), ("Polyne's Breastplate", "Polyne's Breastplate"), ("Saban's Robe", "Saban's Robe"), ("Tersi's Robe", "Tersi's Robe")], max_length=100, verbose_name='PvP Top Armor'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='pvp_tshirt',
            field=models.CharField(blank=True, choices=[('', 'No t-shirt selected'), ("Agility's Anonymous Shirt", "Agility's Anonymous Shirt"), ('Anonymous Shirt of Knowledge', 'Anonymous Shirt of Knowledge'), ('Anonymous Shirt of Strength', 'Anonymous Shirt of Strength'), ('Focus Shirt', 'Focus Shirt'), ('Mithril Shirt of Agility', 'Mithril Shirt of Agility'), ('Mithril Shirt of Knowledge', 'Mithril Shirt of Knowledge'), ('Mithril Shirt of Strength', 'Mithril Shirt of Strength'), ('Vigilante Shirt', 'Vigilante Shirt'), ("Warrior's T-shirt", "Warrior's T-shirt")], max_length=100, verbose_name='PvP T-Shirt'),
        ),
        migrations.AlterField(
            model_name='characterattributes',
            name='weapon',
            field=models.CharField(blank=True, choices=[('', 'No weapon selected'), ('bow|Akatt Longbow', 'Akatt Longbow'), ('bow|Amenance Bow', 'Amenance Bow'), ('bow|Archangel Bow', 'Archangel Bow'), ('bow|Bow of Oblivion', 'Bow of Oblivion'), ('bow|Bow of the Shingung', 'Bow of the Shingung'), ('bow|Bow of the Soul', 'Bow of the Soul'), ('bow|Carnium Bow', 'Carnium Bow'), ('bow|Devils Bow', 'Devils Bow'), ('bow|Elemental Bow', 'Elemental Bow'), ('bow|Giants Bow', 'Giants Bow'), ('bow|Hazard Bow', 'Hazard Bow'), ('bow|Ice Crystal Bow', 'Ice Crystal Bow'), ('bow|Moonlight Bow', 'Moonlight Bow'), ('bow|Plasma Bow', 'Plasma Bow'), ('cane|Archangel Staff', 'Archangel Staff'), ('cane|Bloody Nebulite', 'Bloody Nebulite'), ('cane|Branch of Life', 'Branch of Life'), ('cane|Branches of the World Tree', 'Branches of the World Tree'), ('cane|Commander Staff', 'Commander Staff'), ('cane|Crystal Wand', 'Crystal Wand'), ('cane|Dead Man Staff', 'Dead Man Staff'), ('cane|Desperion Staff', 'Desperion Staff'), ('cane|Ghoul Staff', 'Ghoul Staff'), ('cane|Giant Staff', 'Giant Staff'), ('cane|Imperial Sttaff', 'Imperial Sttaff'), ('cane|Inferno Staff', 'Inferno Staff'), ('cane|Spirit Staff', 'Spirit Staff'), ('chainsword|Archangel Chainsword', 'Archangel Chainsword'), ('chainsword|Barakiel Chainsword', 'Barakiel Chainsword'), ('chainsword|Berseker Chainsword', 'Berseker Chainsword'), ('chainsword|Bultgang', 'Bultgang'), ('chainsword|Chrono Kitara', 'Chrono Kitara'), ('chainsword|Dismentor', 'Dismentor'), ('chainsword|Dragon Hunter', 'Dragon Hunter'), ('chainsword|Gram', 'Gram'), ('chainsword|Lightning Chainsword', 'Lightning Chainsword'), ('chainsword|Nameless Victory', 'Nameless Victory'), ('chainsword|Pain of Gardenness', 'Pain of Gardenness'), ('chainsword|Schrager', 'Schrager'), ('crossbow|Alvarest', 'Alvarest'), ('crossbow|Archangel Crossbow', 'Archangel Crossbow'), ('crossbow|Ballista', 'Ballista'), ('crossbow|Burst Avenger', 'Burst Avenger'), ('crossbow|Crystal Bowgun', 'Crystal Bowgun'), ('crossbow|Doom Singer', 'Doom Singer'), ('crossbow|Giant Crossbow', 'Giant Crossbow'), ('crossbow|Hellhound', 'Hellhound'), ('crossbow|Peacemaker', 'Peacemaker'), ('crossbow|Tasram', 'Tasram'), ('crossbow|Thorn Crossbow', 'Thorn Crossbow'), ('crossbow|antique crossbow', 'antique crossbow'), ('dagger|Archangel Slayer', 'Archangel Slayer'), ('dagger|Blood Orchid', 'Blood Orchid'), ('dagger|Crystal Dagger', 'Crystal Dagger'), ('dagger|Dagger of Contamination', 'Dagger of Contamination'), ('dagger|Dagger of Mana', 'Dagger of Mana'), ('dagger|Devil Dagger', 'Devil Dagger'), ('dagger|Flame Breaker', 'Flame Breaker'), ('dagger|Giant Dagger', 'Giant Dagger'), ('dagger|Hell Knife', 'Hell Knife'), ("dagger|Kruma's Horn", "Kruma's Horn"), ('dagger|Soul Separator', 'Soul Separator'), ('dagger|chris', 'chris'), ('dagger|stiletto', 'stiletto'), ('double_axe|Archangel Twin Axe', 'Archangel Twin Axe'), ('double_axe|Bloody Angish', 'Bloody Angish'), ('double_axe|Bloody Cross', 'Bloody Cross'), ('double_axe|Clarent', 'Clarent'), ('double_axe|Cursed Twin Axe', 'Cursed Twin Axe'), ('double_axe|Furious Berserker', 'Furious Berserker'), ('double_axe|Gallatin', 'Gallatin'), ("double_axe|Giant's Twin Axes", "Giant's Twin Axes"), ('double_axe|Ice Storm Twin Axe', 'Ice Storm Twin Axe'), ('double_axe|Madness Twin Axe', 'Madness Twin Axe'), ('double_axe|Meteor Impact', 'Meteor Impact'), ('double_axe|Warpeak', 'Warpeak'), ('double_axe|Yaksha Twin Axe', 'Yaksha Twin Axe'), ('greatsword|Archangel Buster', 'Archangel Buster'), ("greatsword|Berserker's Greatsword", "Berserker's Greatsword"), ("greatsword|Commander's Greatsword", "Commander's Greatsword"), ('greatsword|Dragon Slayer', 'Dragon Slayer'), ('greatsword|First Blood', 'First Blood'), ('greatsword|Flamberge', 'Flamberge'), ("greatsword|Guardian's Two-Handed Greatsword", "Guardian's Two-Handed Greatsword"), ("greatsword|Heaven's Wingblade", "Heaven's Wingblade"), ('greatsword|Inferno Master', 'Inferno Master'), ('greatsword|Sword of Iphos', 'Sword of Iphos'), ('magic_cannon|Archangel Blaster', 'Archangel Blaster'), ('magic_cannon|Assault Cannon', 'Assault Cannon'), ('magic_cannon|Basilisk Culverin', 'Basilisk Culverin'), ('magic_cannon|Deathbringer', 'Deathbringer'), ('magic_cannon|Divine Blaster', 'Divine Blaster'), ('magic_cannon|Doom Crusher', 'Doom Crusher'), ("magic_cannon|Giant's Blaster", "Giant's Blaster"), ('magic_cannon|Mine Buster', 'Mine Buster'), ('magic_cannon|Pata', 'Pata'), ('magic_cannon|Sarakael Magic Cannon', 'Sarakael Magic Cannon'), ('magic_cannon|Schofield', 'Schofield'), ('magic_cannon|Star Buster', 'Star Buster'), ('magic_cannon|Zephyrus', 'Zephyrus'), ('one_handed_sword|Archangel Blade', 'Archangel Blade'), ('one_handed_sword|Elemental Sword', 'Elemental Sword'), ("one_handed_sword|Fighting Father's Sword", "Fighting Father's Sword"), ("one_handed_sword|Giant's Sword", "Giant's Sword"), ("one_handed_sword|Guardian's Sword", "Guardian's Sword"), ('one_handed_sword|Kshanberg', 'Kshanberg'), ('one_handed_sword|Raid Sword', 'Raid Sword'), ('one_handed_sword|Sir Blade', 'Sir Blade'), ('one_handed_sword|Spirits Sword', 'Spirits Sword'), ('one_handed_sword|Sword of Eclipse', 'Sword of Eclipse'), ('one_handed_sword|Sword of Miracle', 'Sword of Miracle'), ('one_handed_sword|Sword of Nightmare', 'Sword of Nightmare'), ('one_handed_sword|Sword of Valhalla', 'Sword of Valhalla'), ('one_handed_sword|Tsurugi', 'Tsurugi'), ('orb|Archangel Orb', 'Archangel Orb'), ("orb|Devil's Orb", "Devil's Orb"), ('orb|Dragon Flame Head', 'Dragon Flame Head'), ('orb|Eclipse of', 'Eclipse of'), ('orb|Elysion', 'Elysion'), ('orb|Fairy Queen', 'Fairy Queen'), ("orb|Giant's Orb", "Giant's Orb"), ('orb|Hall of Faith', 'Hall of Faith'), ('orb|Hand of Cabrio', 'Hand of Cabrio'), ('orb|Nirvana', 'Nirvana'), ('orb|Spell Breaker', 'Spell Breaker'), ('orb|The Bones of Kaim Banul', 'The Bones of Kaim Banul'), ('rapier|Archangel Rapier', 'Archangel Rapier'), ('rapier|Assault Rapier', 'Assault Rapier'), ('rapier|Blink Rapier', 'Blink Rapier'), ('rapier|Eclair Bijou', 'Eclair Bijou'), ("rapier|Giant's Rapier", "Giant's Rapier"), ('rapier|Glorious', 'Glorious'), ('rapier|Grid Rapier', 'Grid Rapier'), ('rapier|Hauteclair', 'Hauteclair'), ('rapier|Kolishmard', 'Kolishmard'), ('rapier|Levatein', 'Levatein'), ('rapier|Soldat Estark', 'Soldat Estark'), ("rapier|Tromba's Fang", "Tromba's Fang"), ('soul_breaker|Archangel Soul Breaker', 'Archangel Soul Breaker'), ('soul_breaker|Blade of Madness', 'Blade of Madness'), ('soul_breaker|Crystal Soul Breaker', 'Crystal Soul Breaker'), ('soul_breaker|Dark Shadow', 'Dark Shadow'), ('soul_breaker|Frostbite', 'Frostbite'), ("soul_breaker|Giant's Soul Breaker", "Giant's Soul Breaker"), ('soul_breaker|Hrunting', 'Hrunting'), ('soul_breaker|Judge of the Sun', 'Judge of the Sun'), ('soul_breaker|Sword of the Soul', 'Sword of the Soul'), ('soul_breaker|Wisdom of our ancestors', 'Wisdom of our ancestors'), ('spear|Archangel Halberd', 'Archangel Halberd'), ('spear|Ascalon', 'Ascalon'), ('spear|Battle Spear', 'Battle Spear'), ('spear|Body Slasher', 'Body Slasher'), ("spear|Giant's Spear", "Giant's Spear"), ('spear|Great Axe', 'Great Axe'), ('spear|Halberd', 'Halberd'), ('spear|Heavy War Axe', 'Heavy War Axe'), ('spear|Lancia', 'Lancia'), ('spear|Saint Spear', 'Saint Spear'), ('spear|Scorpion', 'Scorpion'), ('spear|Side', 'Side'), ('spear|Tallum Glaive', 'Tallum Glaive'), ('spear|Typhon Spear', 'Typhon Spear'), ('spear|Widowmaker', 'Widowmaker'), ('two_sword_style|Archangel Dual Swords', 'Archangel Dual Swords'), ('two_sword_style|Caribs Dual Swords', 'Caribs Dual Swords'), ('two_sword_style|Damascus Dual Sword', 'Damascus Dual Sword'), ('two_sword_style|Dark Legion', 'Dark Legion'), ('two_sword_style|Death Lord Dual Swords', 'Death Lord Dual Swords'), ("two_sword_style|Giant's Dual Swords", "Giant's Dual Swords"), ('two_sword_style|Homunculus Dual Sword', 'Homunculus Dual Sword'), ("two_sword_style|Mardil's Wrath", "Mardil's Wrath"), ('two_sword_style|Mystery Dual Swords', 'Mystery Dual Swords'), ('two_sword_style|Saint Dual Sword', 'Saint Dual Sword'), ('two_sword_style|Tears of Warrior', 'Tears of Warrior'), ("two_sword_style|Themis's Tongue", "Themis's Tongue")], max_length=100, verbose_name='Weapon'),
        ),
    ]
