# Generated by Django 5.2.7 on 2026-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0057_alter_characterattributes_exp_bow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='soul_prog_accuracy',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-4', '1-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15', '15')], max_length=10, verbose_name='Soul Progression Accuracy'),
        ),
    ]
