# Generated by Django 5.2.7 on 2026-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0058_characterattributes_soul_prog_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Otomatis terbuat event baru untuk minggu depan jika event ini selesai (completed/finalized).', verbose_name='Repeatable Weekly'),
        ),
    ]
