# Generated by Django 5.2.7 on 2026-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0059_activityevent_is_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Jika aktif, anggota yang tidak hadir akan mendapat penalty point.', verbose_name='Mandatory'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='penalty_points',
            field=models.IntegerField(default=5, help_text='Jumlah poin penalty untuk anggota yang tidak hadir di event mandatory.', verbose_name='Penalty Points'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='mandatory_penalty',
            field=models.IntegerField(default=0, help_text='Penalty dari event mandatory yang tidak dihadiri', verbose_name='Mandatory Penalty'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='score_adjustment',
            field=models.IntegerField(default=0, help_text='Penyesuaian manual oleh admin', verbose_name='Score Adjustment'),
        ),
    ]
