# Generated by Django 5.2.7 on 2026-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0060_activityevent_is_mandatory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizepoolconfig',
            name='active_percentage',
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='tier',
            field=models.CharField(choices=[('ELITE', '🏆 Elite'), ('CORE', '⚔️ Core'), ('CASUAL', '🌱 Casual')], default='CASUAL', max_length=20, verbose_name='Tier'),
        ),
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='core_percentage',
            field=models.FloatField(default=0.8, verbose_name='Core %'),
        ),
        migrations.AlterField(
            model_name='prizepoolconfig',
            name='elite_percentage',
            field=models.FloatField(default=0.2, verbose_name='Elite %'),
        ),
    ]
