# Generated by Django 5.2.7 on 2026-03-12 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0061_remove_prizepoolconfig_active_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activityevent',
            name='items_activ_date_538c2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='items_activ_is_comp_5d81cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='items_activ_event_t_1874ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='playeractivity',
            name='items_playe_player__0200c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='playeractivity',
            name='items_playe_event_i_adcc9b_idx',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='balthazar_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='bosses_killed',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='carnifex_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='core_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='custom_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='dragon_beast_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='kain_van_halter_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='latana_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='orfen_points',
        ),
        migrations.RemoveField(
            model_name='activityevent',
            name='penalty_points',
        ),
        migrations.RemoveField(
            model_name='characterattributes',
            name='soul_prog_accuracy',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='base_points',
            field=models.IntegerField(default=5, help_text='Poin dasar untuk attendance', verbose_name='Base Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='boss_killed_count',
            field=models.IntegerField(default=0, verbose_name='Boss Terbunuh'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='boss_point_config',
            field=models.JSONField(blank=True, default=dict, help_text="Config poin per boss, contoh: {'boss1': 5, 'boss2': 10}", verbose_name='Boss Point Config'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Deskripsi'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='mandatory_penalty',
            field=models.IntegerField(default=0, help_text='Penalty jika tidak hadir di event mandatory', verbose_name='Penalty Poin'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='max_points',
            field=models.IntegerField(default=25, help_text='Poin maksimum yang bisa didapat', verbose_name='Max Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='total_bosses',
            field=models.IntegerField(default=0, verbose_name='Total Boss'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='win_bonus',
            field=models.IntegerField(default=10, verbose_name='Bonus Menang'),
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playeractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='date',
            field=models.DateTimeField(verbose_name='Tanggal Event'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Event ID'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INVASION', '⚔️ Invasion'), ('BOSS_RUSH', '🐉 Boss Rush'), ('CATACOMBS', '🏰 Catacombs'), ('DIMENSIONAL', '🌀 Dimensional Siege'), ('CUSTOM', '📋 Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Jika True, poin tidak bisa diubah', verbose_name='Finalized'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Wajib diikuti semua member', verbose_name='Mandatory Event'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Event bisa diulang setiap minggu', verbose_name='Repeatable'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='is_win',
            field=models.BooleanField(default=False, verbose_name='Menang'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Event'),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='bosses_killed',
            field=models.JSONField(blank=True, default=dict, help_text="Track individual boss kills: {'boss1': true, 'boss2': false}", verbose_name='Bosses Killed'),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='discord_user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord User ID'),
        ),
        migrations.AlterField(
            model_name='playeractivity',
            name='status',
            field=models.CharField(choices=[('ATTENDED', '✅ Attended'), ('ABSENT', '❌ Absent')], default='ATTENDED', max_length=20, verbose_name='Status'),
        ),
    ]
