# Generated by Django 5.2.7 on 2026-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0064_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='reward_diamond',
            field=models.BooleanField(default=False, verbose_name='Reward Diamond'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='reward_diamond_points',
            field=models.IntegerField(default=0, verbose_name='Diamond Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='reward_key',
            field=models.BooleanField(default=False, verbose_name='Reward Key'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='reward_key_points',
            field=models.IntegerField(default=0, verbose_name='Key Points'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='reward_membership',
            field=models.BooleanField(default=False, verbose_name='Reward Membership'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='reward_membership_points',
            field=models.IntegerField(default=0, verbose_name='Membership Points'),
        ),
    ]
