# Generated by Django 5.2.7 on 2026-03-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0065_activityevent_reward_diamond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_reset_at', models.DateTimeField(blank=True, help_text='Timestamp of the last weekly reset. Weekly ranking only shows events after this time.', null=True, verbose_name='Weekly Reset At')),
            ],
            options={
                'verbose_name': 'Leaderboard Configuration',
                'verbose_name_plural': 'Leaderboard Configurations',
            },
        ),
    ]
