# Generated by Django 5.2.7 on 2026-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0066_leaderboardconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendarySkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('icon_file', models.CharField(blank=True, max_length=100, verbose_name='File Ikon')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='legendary_skins',
            field=models.ManyToManyField(blank=True, to='items.legendaryskin', verbose_name='Legendary Skins'),
        ),
    ]
