# Generated by Django 5.2.7 on 2026-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0067_legendaryskin_character_legendary_skins'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattributes',
            name='soul_prog_duel',
            field=models.CharField(blank=True, choices=[('1-4', '1-4'), ('5-9', '5-9'), ('10', '10'), ('10.1', '10.1'), ('10.2', '10.2'), ('10.3', '10.3')], max_length=10, verbose_name='Soul Progression Duel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='clan',
            field=models.CharField(blank=True, choices=[('Valkyrie', 'Valkyrie'), ('Einherjar', 'Einherjar')], default='Valkyrie', max_length=100, verbose_name='Clan'),
        ),
    ]
