# Generated by Django 5.2.7 on 2026-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0068_characterattributes_soul_prog_duel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeractivity',
            name='win_streak_bonus',
            field=models.IntegerField(default=0, verbose_name='Win Streak Bonus'),
        ),
    ]
