# Generated by Django 5.2.7 on 2026-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0069_playeractivity_win_streak_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INVASION', '⚔️ Invasion'), ('BOSS_RUSH', '🐉 Boss Rush'), ('CATACOMBS', '🏰 Catacombs'), ('DIMENSIONAL', '🌀 Dimensional Siege'), ('ISLE_AWAKENING', '🏝️ Isle of Awakening'), ('WAR_DAY', '⚔️ War Day'), ('CUSTOM', '📋 Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
    ]
