# Generated by Django 5.2.7 on 2026-04-01 04:05

from django.db import migrations, models


def rename_einherjar_to_valhalla(apps, schema_editor):
    Character = apps.get_model('items', 'Character')
    Character.objects.filter(clan='Einherjar').update(clan='Valhalla')


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0070_add_war_day_event_type'),
    ]

    operations = [
        migrations.RunPython(rename_einherjar_to_valhalla, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='character',
            name='clan',
            field=models.CharField(blank=True, choices=[('Valkyrie', 'Valkyrie'), ('Valhalla', 'Valhalla')], default='Valkyrie', max_length=100, verbose_name='Clan'),
        ),
    ]
