# Generated by Django 5.2.7 on 2026-04-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0072_add_talum_dual_sword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalPowerRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('K1', 'K1'), ('K5', 'K5'), ('K9', 'K9'), ('T8', 'T8')], default='K5', max_length=10, verbose_name='Server')),
                ('power_class', models.CharField(blank=True, help_text='e.g. GS, DB, Orb, Staff, Sword/GS, etc.', max_length=100, verbose_name='Class')),
                ('level', models.FloatField(default=1, verbose_name='Level')),
                ('dmg', models.FloatField(default=0, verbose_name='DMG')),
                ('acc', models.FloatField(default=0, verbose_name='ACC')),
                ('defense', models.FloatField(default=0, verbose_name='DEF')),
                ('dmg_reduct', models.FloatField(default=0, verbose_name='DMG Reduct')),
                ('skill_resist', models.FloatField(default=0, verbose_name='Skill Resist')),
                ('skill_dmg_boost', models.FloatField(default=0, verbose_name='Skill DMG Boost')),
                ('weapon_dmg_boost', models.FloatField(default=0, verbose_name='Weapon DMG Boost')),
                ('soulshot', models.FloatField(default=0, verbose_name='Soulshot')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('guardian', models.FloatField(default=0, verbose_name='Guardian')),
                ('conquer', models.FloatField(default=0, verbose_name='Conquer')),
                ('duel', models.FloatField(default=0, help_text='Duel progression level', verbose_name='Duel')),
                ('purple_class_aga', models.FloatField(default=0, help_text='Number of purple class or agathion', verbose_name='Purple Class/Aga')),
                ('gear_score', models.IntegerField(default=0, help_text='Auto-calculated from stats', verbose_name='Gear Score')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='power_rank', to='items.character')),
            ],
            options={
                'verbose_name': 'Universal Power Rank',
                'verbose_name_plural': 'Universal Power Rankings',
                'ordering': ['-gear_score'],
            },
        ),
    ]
