# Generated by Django 5.2.7 on 2026-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0073_universalpowerrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama player (IGN)', max_length=100)),
                ('rank', models.CharField(choices=[('Master', 'Master'), ('Guardian', 'Guardian'), ('Member', 'Member')], default='Member', max_length=50)),
                ('clan', models.CharField(choices=[('Valkyrie', 'Valkyrie'), ('Valhalla', 'Valhalla')], default='Valkyrie', max_length=50)),
                ('contribution', models.IntegerField(default=0, help_text='Poin kontribusi')),
                ('image', models.ImageField(blank=True, help_text='Gambar karakter/player (aspect ratio Portrait disarankan)', null=True, upload_to='hall_of_fame/')),
                ('is_active', models.BooleanField(default=True, help_text='Tampilkan di halaman Hall of Fame')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hall of Fame Player',
                'verbose_name_plural': 'Hall of Fame',
                'ordering': ['-contribution', 'name'],
            },
        ),
    ]
