# Generated by Django 5.2.7 on 2026-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0074_halloffame'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalpowerrank',
            name='stat_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot dari in-game stat sebagai bukti data valid', null=True, upload_to='power_rank_screenshots/', verbose_name='Stat Screenshot'),
        ),
    ]
