# Generated by Django 5.2.7 on 2026-04-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0075_universalpowerrank_stat_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerRankScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='power_rank_screenshots/', verbose_name='Screenshot')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('power_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='items.universalpowerrank')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
