# Generated by Django 5.2.7 on 2026-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0076_powerrankscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_win_valhalla',
            field=models.BooleanField(default=False, verbose_name='Valhalla Menang'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='is_win_valkyrie',
            field=models.BooleanField(default=False, verbose_name='Valkyrie Menang'),
        ),
    ]
