# Generated by Django 5.2.7 on 2026-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0077_add_per_clan_win_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardconfig',
            name='monthly_reset_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last monthly reset. Monthly ranking only shows events after this time.', null=True, verbose_name='Monthly Reset At'),
        ),
    ]
