# Generated by Django 5.2.7 on 2026-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0078_leaderboardconfig_monthly_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalpowerrank',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Admin check to validate screenshot data matches written data', verbose_name='Data Valid'),
        ),
        migrations.AddField(
            model_name='universalpowerrank',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Alasan jika data tidak valid', null=True, verbose_name='Validation Notes'),
        ),
    ]
