# Generated by Django 5.2.7 on 2026-04-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0079_universalpowerrank_is_validated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(choices=[('Chertuba', 'Chertuba'), ('Kelsus', 'Kelsus'), ('Basilla', 'Basilla'), ('Savan', 'Savan'), ('Tromba', 'Tromba'), ('Felis', 'Felis'), ('Sarka', 'Sarka'), ('Timitris', 'Timitris'), ('Talakin', 'Talakin'), ('Enkura', 'Enkura'), ('Contaminated Cruma', 'Contaminated Cruma'), ('Katan', 'Katan'), ('Stonegheist', 'Stonegheist'), ('Pan Dryad', 'Pan Dryad'), ('Gahareth', 'Gahareth'), ('Valefal', 'Valefal'), ('Breka', 'Breka'), ('Medusa', 'Medusa'), ('Pan Narod', 'Pan Narod'), ('Matura', 'Matura'), ('Black Lily', 'Black Lily'), ('Behemoth', 'Behemoth'), ('Balbo', 'Balbo'), ('Talkin', 'Talkin'), ('Timiniel', 'Timiniel'), ('Selu', 'Selu'), ('Repiro', 'Repiro'), ('Coroon', 'Coroon'), ('Samuel', 'Samuel'), ('Hisilrome', 'Hisilrome'), ('Mirror of Oblivion', 'Mirror of Oblivion'), ('Randor', 'Randor'), ('Glaki', 'Glaki'), ('Cabrio', 'Cabrio'), ('Flynt', 'Flynt'), ('Haff', 'Haff'), ('Phoenix', 'Phoenix'), ('Andras', 'Andras'), ('Thanatos', 'Thanatos'), ('Rahha', 'Rahha'), ('Queen Ant', 'Queen Ant'), ('Mutated Cruma', 'Mutated Cruma'), ('Core Susceptor', 'Core Susceptor'), ('Dragon Beast', 'Dragon Beast'), ('Orfen', 'Orfen'), ('Olkuth', 'Olkuth'), ('Shila', 'Shila'), ('Moof', 'Moof'), ('Normus', 'Normus'), ('Ukanba', 'Ukanba'), ('Selihoden', 'Selihoden'), ('Ramdal', 'Ramdal'), ('Mardil', 'Mardil'), ('Kernon', 'Kernon'), ('Tarim', 'Tarim'), ('Halate', 'Halate'), ('Vella', 'Vella'), ('Shuriel', 'Shuriel'), ('Galaxia', 'Galaxia')], max_length=100, verbose_name='Raid Boss')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souls', to='items.character')),
            ],
            options={
                'verbose_name': 'Character Soul',
                'verbose_name_plural': 'Character Souls',
                'ordering': ['-created_at'],
                'unique_together': {('character', 'boss_name')},
            },
        ),
    ]
