# Generated by Django 5.2.7 on 2026-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0080_charactersoul'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersoul',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='soul_screenshots/', verbose_name='Screenshot Bukti'),
        ),
    ]
