# Generated by Django 5.2.7 on 2026-04-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0081_charactersoul_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSoulProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='soul_proofs/', verbose_name='Screenshot Koleksi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soul_proofs', to='items.character')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
