# Generated by Django 5.2.7 on 2026-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0082_charactersoulproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalpowerrank',
            name='pending_changes',
            field=models.TextField(blank=True, help_text='Catatan perubahan terakhir oleh user', null=True, verbose_name='Pending Changes'),
        ),
    ]
