# Generated by Django 5.2.7 on 2026-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0083_universalpowerrank_pending_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersoul',
            name='boss_name',
            field=models.CharField(choices=[('Anaxa', 'Anaxa'), ('Andras', 'Andras'), ('Balbo', 'Balbo'), ('Basilla', 'Basilla'), ('Behemoth', 'Behemoth'), ('Black Lily', 'Black Lily'), ('Breka', 'Breka'), ('Cabrio', 'Cabrio'), ('Chertuba', 'Chertuba'), ('Contaminated Cruma', 'Contaminated Cruma'), ('Core Susceptor', 'Core Susceptor'), ('Coroon', 'Coroon'), ('Dragon Beast', 'Dragon Beast'), ('Enkura', 'Enkura'), ('Felis', 'Felis'), ('Flynt', 'Flynt'), ('Gahareth', 'Gahareth'), ('Galaxia', 'Galaxia'), ('Glaki', 'Glaki'), ('Haff', 'Haff'), ('Halate', 'Halate'), ('Hisilrome', 'Hisilrome'), ('Katan', 'Katan'), ('Kelsus', 'Kelsus'), ('Kernon', 'Kernon'), ('Kustor', 'Kustor'), ('Mardil', 'Mardil'), ('Matura', 'Matura'), ('Medusa', 'Medusa'), ('Mirror of Oblivion', 'Mirror of Oblivion'), ('Moof', 'Moof'), ('Mutated Cruma', 'Mutated Cruma'), ('Normus', 'Normus'), ('Olkuth', 'Olkuth'), ('Orfen', 'Orfen'), ('Pan Dryad', 'Pan Dryad'), ('Pan Narod', 'Pan Narod'), ('Phoenix', 'Phoenix'), ('Queen Ant', 'Queen Ant'), ('Rahha', 'Rahha'), ('Ramdal', 'Ramdal'), ('Randor', 'Randor'), ('Repiro', 'Repiro'), ('Samuel', 'Samuel'), ('Sarka', 'Sarka'), ('Savan', 'Savan'), ('Selihoden', 'Selihoden'), ('Selu', 'Selu'), ('Shila', 'Shila'), ('Shuriel', 'Shuriel'), ('Stonegheist', 'Stonegheist'), ('Talakin', 'Talakin'), ('Talkin', 'Talkin'), ('Tarim', 'Tarim'), ('Thanatos', 'Thanatos'), ('Timiniel', 'Timiniel'), ('Timitris', 'Timitris'), ('Tromba', 'Tromba'), ('Ukanba', 'Ukanba'), ('Valefal', 'Valefal'), ('Vella', 'Vella')], max_length=100, verbose_name='Raid Boss'),
        ),
    ]
