# Generated by Django 5.2.7 on 2026-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0084_alter_charactersoul_boss_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='mandatory_boss_penalties',
            field=models.JSONField(blank=True, default=dict, help_text="Config penalty per boss untuk event Invasion yg mandatory, contoh: {'Dragon Beast': 5}", verbose_name='Mandatory Boss Penalties'),
        ),
    ]
