# Generated by Django 5.2.7 on 2026-04-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0085_activityevent_mandatory_boss_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='dkp_mandatory_boss_penalties',
            field=models.JSONField(blank=True, default=dict, help_text='Config DKP penalty per boss untuk event Invasion yg mandatory', verbose_name='DKP Mandatory Boss Penalties'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='dkp_mandatory_penalty',
            field=models.IntegerField(default=0, help_text='DKP Penalty jika tidak hadir di event mandatory', verbose_name='DKP Penalty Poin'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='is_dkp_penalty',
            field=models.BooleanField(default=False, help_text='Jika dicentang, penalty juga akan memotong poin DKP', verbose_name='Apply DKP Penalty'),
        ),
    ]
