# Generated by Django 5.2.7 on 2026-04-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0086_activityevent_dkp_mandatory_boss_penalties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeractivity',
            name='dkp_penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
