# Generated by Django 5.2.7 on 2026-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0089_powerrankfarmsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_dkp_system', models.BooleanField(default=False, verbose_name='Enable DKP System Menu')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
            },
        ),
    ]
