# Generated by Django 5.2.7 on 2026-05-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0090_featuretoggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='checkin_token',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Check-in Token'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INV_DRAGON_BEAST', '⚔️ Invasion Dragon Beast'), ('INV_CARNIFEX', '⚔️ Invasion Carnifex'), ('INV_ORFEN', '⚔️ Invasion Orfen'), ('BOSS_RUSH', '🐉 Boss Rush'), ('CATACOMBS', '🏰 Catacombs'), ('DIMENSIONAL', '🌀 Dimensional Siege'), ('ISLE_AWAKENING', '🏝️ Isle of Awakening'), ('WAR_DAY', '⚔️ War Day'), ('CUSTOM', '📋 Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
        migrations.CreateModel(
            name='EventCheckInProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkin_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('detected_party_members', models.TextField(blank=True, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_proofs', to='items.activityevent')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.character')),
            ],
        ),
    ]
