# Generated by Django 5.2.7 on 2026-05-05 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0091_activityevent_checkin_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarPointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_points', models.IntegerField(default=2, verbose_name='Points per Kill')),
                ('assist_points', models.IntegerField(default=1, verbose_name='Points per Assist')),
                ('sync_to_activity', models.BooleanField(default=False, help_text='Jika dicentang, War Points juga akan ditambahkan ke Activity Points player', verbose_name='Sync to Activity Points')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'War Point Config',
                'verbose_name_plural': 'War Point Config',
            },
        ),
        migrations.CreateModel(
            name='WarPointSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='war_points/', verbose_name='Screenshot Bukti')),
                ('war_date', models.DateField(help_text='Tanggal war yang ditampilkan di screenshot', verbose_name='Tanggal War')),
                ('kill_count', models.IntegerField(default=0, help_text='Total kill dari screenshot', verbose_name='Jumlah Kill')),
                ('assist_count', models.IntegerField(default=0, help_text='Total assist dari screenshot', verbose_name='Jumlah Assist')),
                ('kill_points_earned', models.IntegerField(default=0, verbose_name='Kill Points Earned')),
                ('assist_points_earned', models.IntegerField(default=0, verbose_name='Assist Points Earned')),
                ('total_points', models.IntegerField(default=0, verbose_name='Total War Points')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pending Review'), ('APPROVED', '✅ Approved'), ('REJECTED', '❌ Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('synced_to_activity', models.BooleanField(default=False, verbose_name='Synced to Activity')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_submissions', to='items.character')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('character', 'war_date')},
            },
        ),
    ]
