# Generated by Django 5.2.7 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0093_activityevent_input_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='warpointconfig',
            name='auto_delete_days',
            field=models.IntegerField(default=0, help_text='Hapus otomatis image & log setelah N hari (0 = tidak pernah dihapus)', verbose_name='Auto-Delete (Hari)'),
        ),
    ]
