# Generated by Django 5.2.7 on 2026-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0095_playeractivity_attendance_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='scan_info',
            field=models.JSONField(blank=True, default=dict, help_text='Stores OCR party scan result stats (matched/detected) per clan', verbose_name='Scan Info'),
        ),
    ]
