# Generated by Django 5.2.7 on 2026-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0098_split_invasion_mandatory_boss_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardconfig',
            name='active_event_points',
            field=models.IntegerField(default=1200, verbose_name='Active: Min Event Points'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='active_max_slots',
            field=models.IntegerField(default=20, verbose_name='Active: Max Slots'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='active_raid_points',
            field=models.IntegerField(default=300, verbose_name='Active: Min Raid Points'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='core_event_points',
            field=models.IntegerField(default=2050, verbose_name='Core: Min Event Points'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='core_max_slots',
            field=models.IntegerField(default=15, verbose_name='Core: Max Slots'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='core_raid_points',
            field=models.IntegerField(default=300, verbose_name='Core: Min Raid Points'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='elite_event_points',
            field=models.IntegerField(default=2050, verbose_name='Elite: Min Event Points'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='elite_max_slots',
            field=models.IntegerField(default=15, verbose_name='Elite: Max Slots'),
        ),
        migrations.AddField(
            model_name='leaderboardconfig',
            name='elite_raid_points',
            field=models.IntegerField(default=0, verbose_name='Elite: Min Raid Points'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INV_DRAGON_BEAST', 'Invasion Dragon Beast'), ('INV_CARNIFEX', 'Invasion Carnifex'), ('INV_ORFEN', 'Invasion Orfen'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs'), ('DIMENSIONAL', 'Dimensional Siege'), ('ISLE_AWAKENING', 'Isle of Awakening'), ('WAR_DAY', 'War Day'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
    ]
