# Generated by Django 5.2.7 on 2026-05-09 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0099_leaderboardconfig_active_event_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='World Name')),
            ],
            options={
                'verbose_name': 'War World',
                'verbose_name_plural': 'War Worlds',
            },
        ),
        migrations.RemoveField(
            model_name='warpointconfig',
            name='assist_points',
        ),
        migrations.RemoveField(
            model_name='warpointconfig',
            name='kill_points',
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='normal_assist_points',
            field=models.IntegerField(default=2, verbose_name='Normal/Top 6+ Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='normal_kill_points',
            field=models.IntegerField(default=10, verbose_name='Normal/Top 6+ Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top1_assist_points',
            field=models.IntegerField(default=10, verbose_name='Top 1 Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top1_kill_points',
            field=models.IntegerField(default=100, verbose_name='Top 1 Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top1_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 1 Name'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top2_assist_points',
            field=models.IntegerField(default=5, verbose_name='Top 2 Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top2_kill_points',
            field=models.IntegerField(default=50, verbose_name='Top 2 Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 2 Name'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top3_assist_points',
            field=models.IntegerField(default=5, verbose_name='Top 3 Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top3_kill_points',
            field=models.IntegerField(default=50, verbose_name='Top 3 Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top3_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 3 Name'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top4_assist_points',
            field=models.IntegerField(default=5, verbose_name='Top 4 Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top4_kill_points',
            field=models.IntegerField(default=50, verbose_name='Top 4 Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top4_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 4 Name'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top5_assist_points',
            field=models.IntegerField(default=5, verbose_name='Top 5 Assist Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top5_kill_points',
            field=models.IntegerField(default=50, verbose_name='Top 5 Kill Points'),
        ),
        migrations.AddField(
            model_name='warpointconfig',
            name='top5_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 5 Name'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_normal',
            field=models.IntegerField(default=0, verbose_name='Normal Assists'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_top1',
            field=models.IntegerField(default=0, verbose_name='Assist Top 1'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_top2',
            field=models.IntegerField(default=0, verbose_name='Assist Top 2'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_top3',
            field=models.IntegerField(default=0, verbose_name='Assist Top 3'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_top4',
            field=models.IntegerField(default=0, verbose_name='Assist Top 4'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='assist_top5',
            field=models.IntegerField(default=0, verbose_name='Assist Top 5'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_normal',
            field=models.IntegerField(default=0, verbose_name='Normal Kills'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_top1',
            field=models.IntegerField(default=0, verbose_name='Kill Top 1'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_top2',
            field=models.IntegerField(default=0, verbose_name='Kill Top 2'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_top3',
            field=models.IntegerField(default=0, verbose_name='Kill Top 3'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_top4',
            field=models.IntegerField(default=0, verbose_name='Kill Top 4'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='kill_top5',
            field=models.IntegerField(default=0, verbose_name='Kill Top 5'),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='server',
            field=models.IntegerField(default=1, verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='warpointsubmission',
            name='assist_count',
            field=models.IntegerField(default=0, verbose_name='Total Assist'),
        ),
        migrations.AlterField(
            model_name='warpointsubmission',
            name='kill_count',
            field=models.IntegerField(default=0, verbose_name='Total Kill'),
        ),
        migrations.AlterUniqueTogether(
            name='warpointsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='warpointsubmission',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.warworld', verbose_name='World'),
        ),
        migrations.AlterUniqueTogether(
            name='warpointsubmission',
            unique_together={('character', 'world', 'server', 'submitted_at')},
        ),
        migrations.RemoveField(
            model_name='warpointsubmission',
            name='war_date',
        ),
    ]
