# Generated by Django 5.2.7 on 2026-05-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0100_warworld_remove_warpointconfig_assist_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarTargetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.IntegerField(default=1)),
                ('top1_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 1 Name')),
                ('top1_kill_points', models.IntegerField(default=100, verbose_name='Top 1 Kill Points')),
                ('top1_assist_points', models.IntegerField(default=10, verbose_name='Top 1 Assist Points')),
                ('top2_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 2 Name')),
                ('top2_kill_points', models.IntegerField(default=50, verbose_name='Top 2 Kill Points')),
                ('top2_assist_points', models.IntegerField(default=5, verbose_name='Top 2 Assist Points')),
                ('top3_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 3 Name')),
                ('top3_kill_points', models.IntegerField(default=50, verbose_name='Top 3 Kill Points')),
                ('top3_assist_points', models.IntegerField(default=5, verbose_name='Top 3 Assist Points')),
                ('top4_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 4 Name')),
                ('top4_kill_points', models.IntegerField(default=50, verbose_name='Top 4 Kill Points')),
                ('top4_assist_points', models.IntegerField(default=5, verbose_name='Top 4 Assist Points')),
                ('top5_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Top 5 Name')),
                ('top5_kill_points', models.IntegerField(default=50, verbose_name='Top 5 Kill Points')),
                ('top5_assist_points', models.IntegerField(default=5, verbose_name='Top 5 Assist Points')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.warworld')),
            ],
            options={
                'unique_together': {('world', 'server')},
            },
        ),
    ]
