# Generated by Django 5.2.7 on 2026-05-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0101_wartargetconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warpointsubmission',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='war_points/', verbose_name='Screenshot Bukti'),
        ),
        migrations.CreateModel(
            name='WarPointProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='war_points/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_images', to='items.warpointsubmission')),
            ],
        ),
    ]
