# Generated by Django 5.2.7 on 2026-08-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0102_alter_warpointsubmission_screenshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyoutCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_rush_cacomb_pts', models.IntegerField(default=0, verbose_name='Boss Rush & Cacomb Points')),
                ('invasion_boss_pts', models.IntegerField(default=0, verbose_name='Invasion Boss Points')),
                ('veora_pts', models.IntegerField(default=0, verbose_name='Veora Points')),
                ('kustor_pts', models.IntegerField(default=0, verbose_name='Kustor Points')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyout_criteria', to='items.character')),
            ],
        ),
    ]
