# Generated by Django 5.2.7 on 2026-08-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0103_buyoutcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='is_buyout_archived',
            field=models.BooleanField(default=False, help_text='Jika True, poin event ini sudah di-reset dari Buyout Criteria', verbose_name='Archived from Buyout'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INV_DRAGON_BEAST', 'Invasion Dragon Beast'), ('INV_CARNIFEX', 'Invasion Carnifex'), ('INV_ORFEN', 'Invasion Orfen'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs'), ('DIMENSIONAL', 'Dimensional Siege'), ('ISLE_AWAKENING', 'Isle of Awakening'), ('WAR_DAY', 'War Day'), ('VEORA', 'Veora'), ('KUSTOR', 'Kustor'), ('ZHEPAR', 'Zhepar'), ('HARNAK', 'Harnak'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
    ]
