# Generated by Django 5.2.7 on 2026-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0104_activityevent_is_buyout_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('INV_DRAGON_BEAST', 'Invasion Dragon Beast'), ('INV_CARNIFEX', 'Invasion Carnifex'), ('INV_ORFEN', 'Invasion Orfen'), ('BOSS_RUSH', 'Boss Rush'), ('CATACOMBS', 'Catacombs'), ('DIMENSIONAL', 'Dimensional Siege'), ('ISLE_AWAKENING', 'Isle of Awakening'), ('WAR_DAY', 'War Day'), ('VEORA', 'Veora'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Tipe Event'),
        ),
    ]
