# Generated by Django 5.2.7 on 2026-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0105_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalpowerrank',
            name='purple_skill_main_class',
            field=models.FloatField(default=0, help_text='Number of purple skill main class (1-7)', verbose_name='Purple Skill Main Class'),
        ),
    ]
