# Generated by Django 5.2.7 on 2026-02-06 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0032_remove_dkplog_character_remove_dkplog_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DKPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Event')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Open Check-in')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Check-in Closed')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Points Distributed')),
                ('points_to_award', models.IntegerField(default=10, verbose_name='Points Reward')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DKPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_dkp', models.IntegerField(default=0, verbose_name='Current DKP')),
                ('total_earned', models.IntegerField(default=0, verbose_name='Total Earned (Lifetime)')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dkp_profile', to='items.character')),
            ],
            options={
                'verbose_name': 'DKP Profile',
            },
        ),
        migrations.CreateModel(
            name='DKPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Jumlah')),
                ('reason', models.CharField(max_length=255, verbose_name='Alasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dkp.dkpprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DKPAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dkp.dkpevent')),
            ],
            options={
                'verbose_name': 'DKP Attendance',
                'unique_together': {('event', 'character')},
            },
        ),
    ]
