# Generated by Django 5.2.7 on 2026-02-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkpprofile',
            name='last_decay_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='Last Decay %'),
        ),
    ]
