# Generated by Django 5.2.7 on 2026-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0002_dkpprofile_last_decay_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossPointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, verbose_name='Boss Points Config')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Boss Point Config',
            },
        ),
    ]
