# Generated by Django 5.2.7 on 2026-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0003_bosspointconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkpevent',
            name='is_war_day',
            field=models.BooleanField(default=False, verbose_name='War Day'),
        ),
        migrations.AddField(
            model_name='dkpevent',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='dkplog',
            name='is_war_day',
            field=models.BooleanField(default=False, verbose_name='War Day'),
        ),
        migrations.AddField(
            model_name='dkplog',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Catatan'),
        ),
    ]
