# Generated by Django 5.2.7 on 2026-04-07 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0004_dkpevent_is_war_day_dkpevent_note_dkplog_is_war_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryItemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, verbose_name='Treasury Items Config')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Treasury Item Config',
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dkp_admin', models.BooleanField(default=False, help_text='Full access to DKP system (Add, Remove, Decay, etc.)', verbose_name='DKP Admin')),
                ('is_treasury_admin', models.BooleanField(default=False, help_text='Access to Treasury item distribution and DKP deduction', verbose_name='Treasury Admin')),
                ('is_auction_admin', models.BooleanField(default=False, help_text='Access to future Auction system', verbose_name='Auction Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('item_category', models.CharField(max_length=50, verbose_name='Category')),
                ('amount_deducted', models.IntegerField(verbose_name='Amount Deducted')),
                ('currency', models.CharField(default='DKP', max_length=20, verbose_name='Currency')),
                ('clan', models.CharField(default='Valkyrie', max_length=50, verbose_name='Clan')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_logs', to='dkp.dkpprofile')),
            ],
            options={
                'verbose_name': 'Treasury Transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
