# Generated by Django 5.2.7 on 2026-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0005_treasuryitemconfig_adminrole_treasurytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='can_decay_dkp',
            field=models.BooleanField(default=False, verbose_name='Can Decay DKP'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_give_dkp',
            field=models.BooleanField(default=False, verbose_name='Can Give DKP'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='can_remove_dkp',
            field=models.BooleanField(default=False, verbose_name='Can Remove DKP'),
        ),
    ]
