# Generated by Django 5.2.7 on 2026-04-09 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0006_adminrole_can_decay_dkp_adminrole_can_give_dkp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction/', verbose_name='Item Image')),
                ('starting_bid', models.IntegerField(default=100, verbose_name='Starting Bid (DKP)')),
                ('min_increment', models.IntegerField(default=10, verbose_name='Minimum Bid Increment')),
                ('current_bid', models.IntegerField(default=0, verbose_name='Current Highest Bid')),
                ('duration_hours', models.IntegerField(default=24, verbose_name='Duration (Hours)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('clan', models.CharField(default='All', help_text="'All' = both clans can bid, or 'Valkyrie'/'Valhalla' for specific clan", max_length=50, verbose_name='Eligible Clan')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('discord_message_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_leading', to='dkp.dkpprofile')),
            ],
            options={
                'verbose_name': 'Auction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Bid Amount (DKP)')),
                ('is_winner', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False, verbose_name='DKP Refunded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='dkp.auction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='dkp.dkpprofile')),
            ],
            options={
                'verbose_name': 'Auction Bid',
                'ordering': ['-amount'],
            },
        ),
    ]
