# Generated by Django 5.2.7 on 2026-04-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0007_add_auction_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='auction',
            name='duration_minutes',
            field=models.IntegerField(default=60, verbose_name='Duration (Minutes)'),
        ),
    ]
