# Generated by Django 5.2.7 on 2026-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0009_dkpevent_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='is_event_admin',
            field=models.BooleanField(default=False, help_text='Access to Activity Events management', verbose_name='Event Admin'),
        ),
    ]
