# Generated by Django 5.2.7 on 2026-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0010_adminrole_is_event_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='discord_thread_id',
            field=models.CharField(blank=True, help_text='Stored Discord Thread ID', max_length=50, null=True),
        ),
    ]
