# Generated by Django 5.2.7 on 2026-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0011_auction_discord_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(choices=[('DKP', 'DKP'), ('DIAMOND', 'Diamond')], default='DKP', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=100, verbose_name='Starting Bid'),
        ),
    ]
