# Generated by Django 5.2.7 on 2026-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0012_auction_currency_alter_auction_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='is_soul_admin',
            field=models.BooleanField(default=False, help_text='Access to verify/manage Soul collections', verbose_name='Soul Admin'),
        ),
    ]
