# Generated by Django 5.2.7 on 2026-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0013_adminrole_is_soul_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='is_powerrank_admin',
            field=models.BooleanField(default=False, help_text='Access to verify Power Rank entries', verbose_name='Power Rank Admin'),
        ),
    ]
