# Generated by Django 5.2.7 on 2026-04-28 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0014_adminrole_is_powerrank_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Keterangan Item')),
                ('item_type', models.CharField(max_length=100, verbose_name='Tipe Item')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah')),
                ('location', models.CharField(blank=True, default='', help_text='Lokasi / Siapa yang menyimpan', max_length=150, verbose_name='Berada Dimana')),
                ('note', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('clan', models.CharField(default='Valkyrie', max_length=50, verbose_name='Clan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Item',
                'ordering': ['-created_at'],
            },
        ),
    ]
