# Generated by Django 5.2.7 on 2026-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0015_warehouseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='location',
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='item_type',
            field=models.CharField(max_length=100, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
