# Generated by Django 5.2.7 on 2026-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0016_remove_warehouseitem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_proofs/', verbose_name='Screenshot Proof'),
        ),
    ]
