# Generated by Django 5.2.7 on 2026-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0017_warehouseitem_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='is_raidboss_admin',
            field=models.BooleanField(default=False, help_text='Access to input raid boss participation (cannot change boss points)', verbose_name='Raid Boss Admin'),
        ),
    ]
