# Generated by Django 5.2.7 on 2026-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkp', '0018_adminrole_is_raidboss_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='is_warpoint_admin',
            field=models.BooleanField(default=False, help_text='Access to manage War Points', verbose_name='War Point Admin'),
        ),
    ]
